### ISSUE TITLE
Thread stalking

### ISSUE THREAD

**Issue by avalon1337** [HyperDbg/HyperDbg#10]
You should add ring0 thread stalking, so you can do stuff without writing in the binary to supplement the EPT hooks!

**Comment by avalon1337** [comment]
Is it possible to sit on the instruction-chewing function in ntoskrnl.sys or similar? xD

**Comment by SinaKarvandi** [comment]
what do you mean by ring 0 thread stalking? and what is instruction-chewing function?

**Comment by avalon1337** [comment]
The processor uses Fetch->Decode->Execute to process instructions. Do you know where to find the function responsible for this? Does it exist in the cpu rom or a kernel function?

**Comment by SinaKarvandi** [comment]
it's an internal processor function (gate-level).

**Comment by avalon1337** [comment]
> it's an internal processor function (gate-level).

Is it possible to hook it?

**Comment by avalon1337** [comment]
> no, but there are technologies that help to create a log from these instructions, like Intel Processor Trace (PT) or Intel Branch Trace Store (BTS).

What if you attach some kind of hardware to the CPU?

**Comment by SinaKarvandi** [comment]
There is no such hardware (or I don't know), theoretically, it's possible but the processors work on really high clock cycle speed (GHz) and you know, most of the oscilloscopes are working on lower frequencies, even the processor interaction with RAM is on lower clock frequencies but it's still a high speed for normal oscilloscopes and also there is another problem, for example, the processor requests 4 KB of data from RAM and imports it on its cache and you never know how many bytes are fetched and executed. Speculative execution and branch prediction are also problematic.

**Comment by SinaKarvandi** [comment]
The impedance state (High impedance) is another problem that needs to be solved.

**Comment by avalon1337** [comment]
Wow, knew you were the right person to ask. Thank you for the knowledge sharing!
