### ISSUE TITLE
!monitor command not working for big ranges

### ISSUE THREAD

**Issue by m853ax** [HyperDbg/HyperDbg#104]
Tried to monitor r a range of addresses bigger then 0x1000 and got `Error (EptHookPerformPageHook2:795) | Err, there is no pre-allocated buffer available`. is there anyway of fixing this?

**Comment by SinaKarvandi** [comment]
Hello,
Are you using the latest commits from the master branch?

**Comment by m853ax** [comment]
gonna try with the latest
