### ISSUE TITLE
شرایط استفاده در توزیع لینوکس predator-os

### ISSUE THREAD

**Issue by hosseinseilani** [HyperDbg/HyperDbg#108]
با سلام 
پروژه خوب شما رو  دیدم.
آیا امکانش هست من از این نسخه برنامه شما در توزیع لینوکس
**www.predator-os.com**
استفاده نمایم؟
این توزیع لینوکس را در زمینه تست نفوذ و حوزه حریم خصوصی ایجاد کردم.
در توزیع  دسته بندی برای ابزارهای حوزه دیباگ دارم.
خوشحال میشم که این ابزار را نیز به مجموعه ابزارهای توزیع  اضافه کنم.

**https://www.aparat.com/v/BzuUm**

**Comment by SinaKarvandi** [comment]
Hi,
Thanks for creating this issue.
Even though I understand Persian, it's better to keep the conversation in English based on community guidelines and as many people might want to read it.
The answer is No, HyperDbg only works on Windows. Even though we have a plan to release it for Linux in the future but we still have a long road to reach a Linux version.
Also, would you please send me an email at `sina@rayanfam.com` for further discussions?

Thanks,

**Comment by hosseinseilani** [comment]
Hi Sina.
Thanks for answering.
Yes sure.
I emailed you.
