### ISSUE TITLE
Two bugs

### ISSUE THREAD

**Issue by wuhao13** [HyperDbg/HyperDbg#12]
EptHookInstructionMemory BUG

```
    InsertHeadList(&g_EptHook2sDetourListHead, &(DetourHookDetails->OtherHooksList));

    //
    // Write the absolute jump to our shadow page memory to jump to our hook
    //
    EptHookWriteAbsoluteJump(&Hook->FakePageContents[OffsetIntoPage], (SIZE_T)HookFunction);

    return TRUE;
```

fix

```
    InsertHeadList(&g_EptHook2sDetourListHead, &(DetourHookDetails->OtherHooksList));

    //
    // Write the absolute jump to our shadow page memory to jump to our hook
    //
    EptHookWriteAbsoluteJump2(&Hook->FakePageContents[OffsetIntoPage], (SIZE_T)HookFunction);

    return TRUE;
```

SyscallHookTest() bug

```
    if (EptHook2(ApiLocationFromSSDTOfNtCreateFile, NtCreateFileHook, PsGetCurrentProcessId(), (PVOID *)&NtCreateFileOrig, FALSE, FALSE, TRUE))
    {
        LogInfo("Hook appkied to address of API Number : 0x%x at %llx\n", ApiNumberOfNtCreateFile, ApiLocationFromSSDTOfNtCreateFile);
    }
```

fix
`    if (EptHook2(ApiLocationFromSSDTOfNtCreateFile, NtCreateFileHook, PsGetCurrentProcessId(), FALSE, FALSE, TRUE))`

**Comment by wuhao13** [comment]
Hello, thank you for your sharing. Can you optimize the performance of EPT hook and provide a demo of efer hook

**Comment by SinaKarvandi** [comment]
efer hook is like: '`!syscall code {90}`' or  '`!syscall 9a code {90}`' where `9a` is an example of syscall.
`SyscallHookTest() `bug : This function is not used anymore.
also about the first bug, please provide me a case when you see the error (how did you use it?),
I mean it doesn't have any error for me.

**Comment by wuhao13** [comment]
Thank you for your reply. I modified EPT hook to make it work properly, but I found that this method greatly affected the performance of windows. Now I have given up using it.
