### ISSUE TITLE
Bug:EptHookUnHookSingleAddress

### ISSUE THREAD

**Issue by wuhao13** [HyperDbg/HyperDbg#13]
Removeentrylist() should remove templist instead of hookedentry - > PageHookList.Flink

`RemoveEntryList(TempList)`

**Comment by xuxiangbin** [comment]
but why and where?

**Comment by wuhao13** [comment]
Use remove entry list (hooked entry - >) PageHookList.Flink ）Incorrect removal will cause an exception when setting breakpoints repeatedly

**Comment by wuhao13** [comment]
`		else if (HookedEntry->IsHiddenMemoryEdit)
		{
			//
			// It's a hidden breakpoint (we have to search through an array of addresses)
			//
			for (size_t i = 0; i < HookedEntry->CountOfMemoryEdit; i++)
			{
				if (HookedEntry->HiddenMemoryEditAddresses[i] == VirtualAddress)
				{
					//
					// We found an address that matches this entry
					//

					//
					// Check if it's a single breakpoint
					//
					if (HookedEntry->CountOfMemoryEdit == 1)
					{
						//
						// Remove the hook entirely on all cores
						//
						KeGenericCallDpc(HvDpcBroadcastRemoveHookAndInvalidateSingleEntry, HookedEntry->PhysicalBaseAddress);

						//
						// remove the entry from the list
						//
						
						if (!RemoveEntryList(TempList))
						{

						}
						//
						// we add the hooked entry to the list
						// of pools that will be deallocated on next IOCTL
						if (!PoolManagerFreePool(HookedEntry))
						{
							LogError("Something goes wrong ! the pool not found in the list of previously allocated pools by pool manager.");
						}

						return TRUE;
					}
					else
					{
						//
						// Set 0xcc to its previous value
						//
						TargetAddressInFakePageContent = &HookedEntry->FakePageContents;
						TargetAddressInFakePageContent = PAGE_ALIGN(TargetAddressInFakePageContent);
						PageOffset = PAGE_OFFSET(VirtualAddress);
						TargetAddressInFakePageContent = TargetAddressInFakePageContent + PageOffset;

						//
						// Set the previous value
						//
						//*(BYTE *)TargetAddressInFakePageContent = HookedEntry->PreviousBytesOnBreakpointAddresses[i];

						//
						// Remove just that special entry
						// Btw, No need to remove it, it will be replace automatically
						//
						HookedEntry->HiddenMemoryEditAddresses[i] = NULL;
						//	HookedEntry->PreviousBytesOnBreakpointAddresses[i] = 0x0;

						//
						// all addresses to a lower array index (because one entry is
						// missing and might) be in the middle of the array
						//
                        for (size_t j = i; j < MaximumHiddenEditMemeory - 1; j++)
						{
							HookedEntry->HiddenMemoryEditAddresses[j] = HookedEntry->HiddenMemoryEditAddresses[j + 1];
							//HookedEntry->PreviousBytesOnBreakpointAddresses[j] = HookedEntry->PreviousBytesOnBreakpointAddresses[j + 1];
						}

						//
						//
						HookedEntry->CountOfMemoryEdit = HookedEntry->CountOfMemoryEdit - 1;

						return TRUE;`

**Comment by wuhao13** [comment]
```
                        KeGenericCallDpc(HvDpcBroadcastRemoveHookAndInvalidateSingleEntry, HookedEntry->PhysicalBaseAddress);

                        //
                        // remove the entry from the list
                        //

						//if (!RemoveEntryList(HookedEntry->PageHookList.Flink))
						if (!RemoveEntryList(TempList))
						{
							
						}
						//RemoveTailList()
						
                        //
                        // we add the hooked entry to the list
                        // of pools that will be deallocated on next IOCTL
                        if (!PoolManagerFreePool(HookedEntry))
                        {
                            LogError("Something goes wrong ! the pool not found in the list of previously allocated pools by pool manager.");
                        }
```
