### ISSUE TITLE
Crashed inside hyper-v's guest machine when load vmm

### ISSUE THREAD

**Issue by gmh5225** [HyperDbg/HyperDbg#135]
**Describe the bug**
Crashed inside hyper-v's guest machine when load vmm
Vritualize Platform: Hyper-v with Nested Virtualization
Host OS: 19041
Guest OS: 17763 or 19041

**To Reproduce**
1. Install Hyper-V Manager in your host OS
2. Install guest OS by Hyper-V
3. Enable Nested Virtualization 'Set-VMProcessor -VMName $yourvmname -ExposeVirtualizationExtensions $true'
4. Run hyperdbg-cli.exe inside guest os and load vmm by local mode
5. See error

**Expected behavior**
Guest OS will crash

**Screenshots**
VM crashed

**Desktop (please complete the following information):**
 - Host OS: 19041
 - Guest OS: 17763 or 19041
 - Processor [Intel i9-12900K]
 - Version [hyperdbg master]
 - Environment [Hyper-v with Nested Virtualization]

**Comment by gmh5225** [comment]
> 

Looks like it crashes after entering hyper-v's vm-exit processing.

**Comment by gmh5225** [comment]
Tested DBVM & Hyperplatform. They all crashed.

**Comment by SinaKarvandi** [comment]
Hi,
It's a really tough issue!
I know that it exists. However, I didn't try to solve it yet.
That's a priority, but I have to spend weeks on it to find the problem. Previously I concluded that there was a problem with Hyper-V's EPT invalidation but didn't work on it for at least one year.
So, I'll keep this issue open to solve this problem as it has a huge impact on the usage of HyperDbg.
Please keep me informed if you find any solution or hint on the Hyper-V support. 
I'll get into it after the first public, probably the following weeks, and keep you informed about its progress.

Thanks for creating this issue,

**Comment by gmh5225** [comment]
> Hi, It's a really tough issue! I know that it exists. However, I didn't try to solve it yet. That's a priority, but I have to spend weeks on it to find the problem. Previously I concluded that there was a problem with Hyper-V's EPT invalidation but didn't work on it for at least one year. So, I'll keep this issue open to solve this problem as it has a huge impact on the usage of HyperDbg. Please keep me informed if you find any solution or hint on the Hyper-V support. I'll get into it after the first public, probably the following weeks, and keep you informed about its progress.
> 
> Thanks for creating this issue,

OK. I will debug this problem in my spare time.

**Comment by gmh5225** [comment]
The problem has been solved.   :)
Just upgrade the host OS to Win11(My version:10.0.22000.556).

I debugged it by USB and found maybe the old OS did not support Nested Virtualization fully. 
So trying to upgrade OS and it works well.

**Comment by SinaKarvandi** [comment]
Oh, great!
Also, is the guest OS a Win 10 or a Win 11?

**Comment by gmh5225** [comment]
> Oh, great! Also, is te guest OS a Win 10 or a Win 11?
Mine is OK. (17763 Win10)

**Comment by gmh5225** [comment]
> Oh, great! Also, is the guest OS a Win 10 or a Win 11?

Mine is OK.(17763 Win10)
