### ISSUE TITLE
BUG:IRQL-NOT-LESS-OR EQUAL

### ISSUE THREAD

**Issue by wuhao13** [HyperDbg/HyperDbg#14]
```
AsmVmxoffHandler PROC
    sub rsp, 020h       ; shadow space
    call HvReturnStackPointerForVmxoff
    add rsp, 020h       ; remove for shadow space

    mov [rsp+198h], rax  ; now, rax contains rsp <- this!
```

calls:
```
nt!KeBugCheckEx
nt!setjmpex+0x6dc9
nt!setjmpex+0x3f06
hprdbghv!AsmVmxoffHandler+0xd

```

The error occurs when it stops

Complete Dump please contact 6192122@qq.com

thank you！

**Comment by SinaKarvandi** [comment]
what did you do that you see this error? did you execute 'unload' command ?

**Comment by wuhao13** [comment]
yes！I send IOCTL_TERMINATE_VMX

**Comment by SinaKarvandi** [comment]
ok, I not really test HyperDbg that much yet, but sure take a look.

**Comment by wuhao13** [comment]
I tested normal in VMware, but this problem occurred on the physical computer.
