### ISSUE TITLE
[Question] About the reason of EPT Misconfiguration

### ISSUE THREAD

**Issue by L1B0** [HyperDbg/HyperDbg#142]
Hi, I have a question about [this line of code](https://github.com/HyperDbg/HyperDbg/blob/22bd39f35025c856dda28e3c130f64a0516b8417/hyperdbg/hprdbghv/code/debugger/features/hooks/ept-hook/EptHook.c#L1015), it says  SetHookForWrite and !SetHookForRead will cause EPT Misconfiguration, which means set one page that can't be writen but can read . As well as it set read access to 1 and write access to 0, which is contrary to what the Intel SDM says: `Bit 0 of the entry is clear (indicating that data reads are not allowed) and bit 1 is set (indicating that data writes are allowed.`

Hope for your reply!
Thanks!

**Comment by L1B0** [comment]
Thanks for your reply! But I have a question yet.
Based on the Intel WDM, if a page that can't be read but can be written, it will cause a EPT Misconfiguration.
Why should a page be not readable if it's not writable? That's what I'm confused.

**Comment by L1B0** [comment]
In my understanding, the SDM means if we want to set a reading hook(Bit 0 of the entry is clear), we should also set a writing hook(Bit 0 of the entry is clear). Because if a page can't be readable, how can it be writable? That' what I think:-)

**Comment by L1B0** [comment]
Besides, I have tried to set a page in two ways just recently:
1.  SetHookForRead = TRUE, SetHookForWrite = FALSE, it causes EptHandleMisconfiguration.
```
0: kd> g
Break instruction exception - code 80000003 (first chance)
MyHypervisorDriver!EptHandleMisconfiguration+0x6d:
fffff805`3bc51dcd cc              int     3
```
2.  SetHookForRead = FALSE, SetHookForWrite = TRUE, it works.

**Comment by SinaKarvandi** [comment]
yes, you're right!

The logic should be changed to prevent : `SetHookForRead = TRUE, SetHookForWrite = FALSE`

We would be happy if you want to fix it by yourself and send a pull request! 

Thanks a lot for such a precise inspection of the source code.

**Comment by L1B0** [comment]
I have made a request for it. 
As well as Hypervisor From Scratch has this bug:-)
Thanks!
