### ISSUE TITLE
I am just curious,what will happen if i monitor the whole kernel space with unread and unwrite

### ISSUE THREAD

**Issue by Frankenstein-bit** [HyperDbg/HyperDbg#15]
Actually, I just read the part of the code,and I think if I set the whole kernel space unread and unwrite,the software may get stuck.
Am i right

**Comment by SinaKarvandi** [comment]
I don't understand you completely but if you mean setting all unread/unwrite bits of EPT then it's possible but makes the system slow (like a halt).

**Comment by Frankenstein-bit** [comment]
here is the example :I set the monitor range be FFFFF700`00000000~   FFFFFFFF`FFFFFFFF. It not only about slow,it about some interrupt you do not handle in mtf handle.

**Comment by SinaKarvandi** [comment]
Sorry for the delay. What do you mean by the interrupt that I didn't handle in mtf ? I mean interrupt and mtf are two separate and unrelated thing.

**Comment by Frankenstein-bit** [comment]
Yes,you are right.It's my mistake.
