### ISSUE TITLE
vmread VM_INSTRUCTION_ERROR after vmofff will cause 0xc000001d

### ISSUE THREAD

**Issue by L1B0** [HyperDbg/HyperDbg#159]
**Describe the bug**
In [hyperdbg/hprdbghv/code/vmm/vmx/Vmx.c#L422](https://github.com/HyperDbg/HyperDbg/blob/affb2e206d7aba85c690b4e7bd202fe9cc5447e5/hyperdbg/hprdbghv/code/vmm/vmx/Vmx.c#L422), it executes vmoff, and then it uses vmread from VMCS[VMCS_VM_INSTRUCTION_ERROR] to get the errorcode, but at this point vm is already been off, which will causes "Illegal instruction - code c000001d" in windbg. 

**To Reproduce**
1. Make some illegal settings to VMCS.
2. Install driver and run MyhypervisorApp.exe
3. See error in windbg

**Expected behavior**
Just move the vmoff code to after vmread(VM_INSTRUCTION_ERROR), and we can get the error code.

**Original Code**
```
    __vmx_off();

    __vmx_vmread(VMCS_VM_INSTRUCTION_ERROR, &ErrorCode);
    LogError("Err, unable to execute VMLAUNCH, status : 0x%llx", ErrorCode);

    LogError("Err, VMXOFF Executed Successfully but it was because of an error");
```

**After Fixed**
```
    __vmx_vmread(VMCS_VM_INSTRUCTION_ERROR, &ErrorCode);
    LogError("Err, unable to execute VMLAUNCH, status : 0x%llx", ErrorCode);

    __vmx_off();
    LogError("Err, VMXOFF Executed Successfully but it was because of an error");
```

**Comment by SinaKarvandi** [comment]
Hi,
Thanks for creating this issue.
Yep, you're right. Please submit your pull request with the above fix to the 'dev' branch.

Thanks,
