### ISSUE TITLE
 Feedback on a blue screen bug

### ISSUE THREAD

**Issue by wuhao13** [HyperDbg/HyperDbg#16]
There are many calls with too many parameters in your code. After fixing these calls, the blue screen problem appears here. I hope you can fix it.

`    

        movaps xmm0, xmmword ptr [rsp+000h]
        movaps xmm1, xmmword ptr [rsp+010h]
        movaps xmm2, xmmword ptr [rsp+020h]
        movaps xmm3, xmmword ptr [rsp+030h]
        movaps xmm4, xmmword ptr [rsp+040h]
        movaps xmm5, xmmword ptr [rsp+050h]
        movaps xmm6, xmmword ptr [rsp+060h]
        movaps xmm7, xmmword ptr [rsp+070h]
        movaps xmm8, xmmword ptr [rsp+080h]
        movaps xmm9, xmmword ptr [rsp+090h]
        movaps xmm10, xmmword ptr [rsp+0a0h]
        movaps xmm11, xmmword ptr [rsp+0b0h]
        movaps xmm12, xmmword ptr [rsp+0c0h]
        movaps xmm13, xmmword ptr [rsp+0d0h]
        movaps xmm14, xmmword ptr [rsp+0e0h]
        movaps xmm15, xmmword ptr [rsp+0f0h]

        ldmxcsr dword ptr [rsp+0100h]          《-This
        
        add     rsp, 0110h
    ; ----------------------------------------------

    popfq

	pop		rsp     ; restore rsp
	ret             ; jump back to where we called Vmcall

AsmVmxoffHandler ENDP
`

**Comment by SinaKarvandi** [comment]
Thank you for sending us the buggy code. we are not yet in the testing phase so, I'll solve them all soon when we reach the testing phase.
