### ISSUE TITLE
Kernel Panic introduced

### ISSUE THREAD

**Issue by Rwkeith** [HyperDbg/HyperDbg#165]
**Describe the bug**
On `load vmm`, kernel panic with error `WHEA_UNCORRECTABLE_ERROR`

**To Reproduce**
Introduced somewhere between commits:
9ee4f34dbb1a1b3db061376d1d92d868e2775d2f April 5th (working)
14c67642188e47c31b82294d63c53d467d2d6115 April 8th (fails)

**Expected behavior**
HyperDbg> load vmm
loading the vmm driver
current processor vendor is : GenuineIntel
virtualization technology is vt-x
vmx operation is supported by your processor
vmm module is running...
interpreting symbols and creating symbol maps
please configure the symbol path (use '.help .sympath' for more information)

**Desktop (please complete the following information):**
 - OS: Win 10 21H1 Build 19044]
 - Processor Intel i7 8750H
 - Physical Machine

Crash dump can be provided directly

**Comment by SinaKarvandi** [comment]
Hi, 
Thanks a lot for creating this issue.

My first guess is that the error is related to the segment changes (cc @BehroozAbbassi) by the timeline you provided.
However, the thing is, I checked it on both physical machines and VMware nested-virtualization, and I cannot reproduce the error. Thus, it's tough to give a solution. However, you can help us.

     1. Would you please test the latest commits (in the 'dev' branch) and tell me if you have the same problem on the latest commit or not?
     2. If you have the problem in the newest versions, can you give us the exact commit that causes this problem? To do this, you should checkout to previous commits and build HyperDbg and check if the commit has a problem. Like a binary search, you can find the exact commit by dividing each commit history by two each time.

Thanks again.

**Comment by Rwkeith** [comment]
Found failing commit by binary searching testing: 38bef6396bc98d0e1af67fc35908c42b7b3f656e, [April ](https://github.com/HyperDbg/HyperDbg/commit/38bef6396bc98d0e1af67fc35908c42b7b3f656e)

Steps to reproduce:
git clone --recursive https://github.com/HyperDbg/HyperDbg.git

git reset --hard 38bef6396bc98d0e1af67fc35908c42b7b3f656e

load project hyperdbg.sln into VS 2019
Set kdserial project settings to test sign, SHA256 signing
build


run hyperdbg-cli.exe
.sympath SRV*c:\Symbols*https://msdl.microsoft.com/download/symbols
.sym reload
.connect local
unload remove vmm
load vmm

**Comment by SinaKarvandi** [comment]
Thanks to your contribution, the problem is now solve : https://github.com/HyperDbg/HyperDbg/commit/cfebfe27f983b2409abde536c99d4983611be166
