### ISSUE TITLE
The EferHook problem could not be closed properly

### ISSUE THREAD

**Issue by wuhao13** [HyperDbg/HyperDbg#19]
Hello, I found a problem about closing the EferHook blue screen.The problem is that the system continues to generate #UD exceptions when SyscallEnable is set to True.

**Comment by wuhao13** [comment]
In the AsmVmexitHandle, you removed the XMM airflow instead of timely altering the AsmVmxoffHandler's airflow 198h, which resulted in a damaged stack when the discharge occurred.

**Comment by wuhao13** [comment]
Bug Fix
`    sub rsp, 020h       ; shadow space
    call HvReturnStackPointerForVmxoff
    add rsp, 020h       ; remove for shadow space

    mov [rsp+88h], rax  ; now, rax contains rsp

    sub rsp, 020h       ; shadow space
    call HvReturnInstructionPointerForVmxoff
    add rsp, 020h       ; remove for shadow space

    mov rdx, rsp        ; save current rsp

    mov rbx, [rsp+88h] ; read rsp again

    mov rsp, rbx

    push rax            ; push the return address as we changed the stack, we push
                        ; it to the new stack

    mov rsp, rdx        ; restore previous rsp
                        
    sub rbx,08h         ; we push sth, so we have to add (sub) +8 from previous stack
                        ; also rbx already contains the rsp
    mov [rsp+88h], rbx ; move the new pointer to the current stack
`

**Comment by SinaKarvandi** [comment]
@wuhao13  Would you plz push a pull request?

**Comment by wuhao13** [comment]
Sorry, I will not push.

**Comment by wuhao13** [comment]
In addition, can you help fix the EFER HOOK closing problem? I need to use this feature now.

**Comment by SinaKarvandi** [comment]
Fixed! See the latest commit.
The problem was because we didn't save or load EFER on vm-exits so the EFER.SyscallEnable remained to FALSE which causes unhandled #UD errors.
Please double check to see if it works for you.

**Comment by wuhao13** [comment]
Thank you, it's wee hours in Asia now, so I will verify the problem tomorrow.good night！

**Comment by SinaKarvandi** [comment]
You're welcome. :)

**Comment by wuhao13** [comment]
Thanks for your technical help, the problem has been solved after testing

**Comment by SinaKarvandi** [comment]
Thanks to you for reporting.
