### ISSUE TITLE
Feature Request: Support Instruction Tracking

### ISSUE THREAD

**Issue by romanholidaypancakes** [HyperDbg/HyperDbg#195]
**Is your feature request related to a problem? Please describe.**
na

**Describe the solution you'd like**
I want to keep track of all executed instructions within a process, 

**Describe alternatives you've considered**
Like `ultimap` function of `cheatengine`

**Additional context**
![image](https://user-images.githubusercontent.com/51652878/185848589-59c0363b-fa35-4b54-8bb8-9709c611fd27.png)

**Comment by SinaKarvandi** [comment]
Hi,
Thanks a lot for creating this issue.

Would you please describe a little bit more about Ultimap? What does it do?

Thanks

**Comment by SinaKarvandi** [comment]
I get what you mean.

Do you know how they implement it? I mean, do they use the Trap flag to instrument instructions?

**Comment by SinaKarvandi** [comment]
Thanks a lot. I'll look at the source code, add this feature to the TODO list to be implemented in the future version, and update you on this issue.

**Comment by BlackLuny** [comment]
My project for intel pt，you can reference it：
-[]()

**Comment by SinaKarvandi** [comment]
The requested feature is now available in HyperDbg. You can now, intercept the execution of your target binary.

Please, use the v0.4. It's currently in the 'dev' branch, through the !monitor command.

https://docs.hyperdbg.org/commands/extension-commands/monitor

Make sure to re-open the issue if this execution interception doesn't satisfy your needs.

https://docs.hyperdbg.org/commands/extension-commands/monitor
