### ISSUE TITLE
Add sysenter hook & monitor

### ISSUE THREAD

**Issue by duowen1** [HyperDbg/HyperDbg#20]
We can run 32-bit application on our x64  Windows systems, but 32-bit applications use sysenter to do system call. Is there anyway to hook or monitor sysenter/sysexit in your hypervisor?

**Comment by wuhao13** [comment]
In a 32-bit system, sysenter performs some conversions in the wow64 process and then calls syscall to enter the kernel

**Comment by SinaKarvandi** [comment]
As @wuhao13 mentioned, in x64 machines Syscall is used for both x86 and x64. Search for heaven gate.

**Comment by SinaKarvandi** [comment]
And also, HyperDbg is completely an x64 Debugger right now.

**Comment by wuhao13** [comment]
You can refer to this article, but unfortunately, he is in Chinese
[https://blog.wuhao13.xin/2355.html](url)

**Comment by duowen1** [comment]
@wuhao13  @SinaKarvandi  thanks, it is my mistake.
