### ISSUE TITLE
Using HyperDbg in a VMware virtual machine to debug another VMWare virtual machine

### ISSUE THREAD

**Issue by begnoob123** [HyperDbg/HyperDbg#204]
I am having trouble trying to use HyperDbg set up in a VMWare virtual machine to debug another VMWare virtual machine. I get the error "err, occurred while connecting to the server (2) is virtual machine running?"

1. Set the virtual serial port for the debugger and debuggee VMWare VMs and set the named pipe name to \\.\pipe\com_1. THe debugger is set as the client and the debuggee is set as the server. 
![image](https://user-images.githubusercontent.com/119290010/204230534-c45936af-151e-4153-9467-c1756d8db9f0.png)
![image](https://user-images.githubusercontent.com/119290010/204230604-9300a175-051f-4365-93bd-0e8f55eca619.png)
3. Turn on the debuggee machine. 
4. Execute the hyperdbg-cli.exe in the debugger machine and run the command ".debug remote namedpipe \\.\pipe\com_1"
5. Error of "err, occurred while connecting to the server (2) is virtual machine running?"
![image](https://user-images.githubusercontent.com/119290010/204230388-73900df6-2a17-4ba9-bff2-54eba5a05806.png)

**Comment by SinaKarvandi** [comment]
Hi,
Thanks for opening this issue.
Well, I didn't test it like this, but as long as I know, VMware exports named pipes as COM ports in the virtual machine (not in the host). I'm not sure if it's correct for this scenario, but can you test whether the `\\.\pipe\com_1` is a valid named pipe in the target virtual machine or not?

**Comment by SinaKarvandi** [comment]
That's great.
