### ISSUE TITLE
HyperDbg hang

### ISSUE THREAD

**Issue by begnoob123** [HyperDbg/HyperDbg#205]
Hi, I have been trying out the examples provided in the HyperDbg documentation. But when i was doing the example on the !epthook, HyprDbg on my debugger machine seems to hang and becomes unresponsive. My target machine also remains in 'break' mode. 

1. Follow the instructions to attach to a remote machine in HyperDbg Documentation. https://docs.hyperdbg.org/getting-started/attach-to-hyperdbg/debug
2. Follow the example on the !epthook example. https://docs.hyperdbg.org/commands/extension-commands/epthook
3. At the step where they set the epthook on the nt!NtOpenFile. HyperDbg hangs.
![HyperDbg_hang](https://user-images.githubusercontent.com/119290010/205230902-6d55ef0a-2cd2-4b9b-8425-a660d48489b1.png)

I am using a VMware VM to debug another VMware VM. Both VMs' OS is win10 21h2, intel i7-9700.

**Comment by begnoob123** [comment]
I don't think this is limited to that command as the HyperDbg hang happened quite a few times while I was doing other commands as well. For example, I tried to step to the next instruction using the p command and HyperDbg hanged as well.

**Comment by ddkwork** [comment]
run first？

**Comment by begnoob123** [comment]
Hi, sorry what do you mean by run first?

**Comment by ddkwork** [comment]
> Hi, sorry what do you mean by run first?

I'm not sure. When I first used hyperdbg, I also seemed to encounter this problem. My impression was that I executed the script command: run, let the virtual machine run first, and then perform other operations such as hooking and debugging. Although this process was blue screen several times, I could correctly execute the hooking and debugging logic.

**Comment by begnoob123** [comment]
that's interesting. I will try that and see if HyperDbg hangs again. Thank you!
