### ISSUE TITLE
Address might be valid but not present in the ram

### ISSUE THREAD

**Issue by begnoob123** [HyperDbg/HyperDbg#208]
I am currently trying to debug something and am trying to set a breakpoint on a function. But I get this error: "err, edit memory request has invalid address based on current process layout, the address might be valid but not present in the ram." When I try to set an epthook on the same function, i get an invalid address error.

May I know what are the possible problems that may cause this error?

**Comment by SinaKarvandi** [comment]
Hi,
The reason for this error code is that the address is not valid. Most of the time, it indicates that you're in the wrong process layout (CR3), and the address is not mapped based on your current process. 

You can use the ".process" command to see the current process and probably switch to the memory layout of your target process. Other possible options would be to trigger a special event (say !syscall) and filter it by process id, and when the process id triggers the event, you're in the memory layout of the target process, and you can use breakpoint.

**Comment by begnoob123** [comment]
Hi, thank you for the reply. I tried using the .process command to switch to my target process but I still get the same error. I came across this page on the HyperDbg documentation on switching to a new process memory layout. https://docs.hyperdbg.org/tips-and-tricks/misc/switch-to-new-process-layout
Is this method still not usable?

But the syscall method worked for me. Thank you!
