### ISSUE TITLE
1

### ISSUE THREAD

**Issue by solitudecc** [HyperDbg/HyperDbg#209]
BOOLEAN
GlobalEventsAllocateZeroedMemory(VOID)
{
    //
    // Allocate buffer for saving events
    //
    if (!g_Events)
    {
        g_Events = ExAllocatePoolWithTag(NonPagedPool, sizeof(DEBUGGER_CORE_EVENTS), POOLTAG);
    }

    if (!g_Events)  //<----------------------------"!" Shouldn't this be needed?
    {
        //
        // Zero the buffer
        //
        RtlZeroBytes(g_Events, sizeof(DEBUGGER_CORE_EVENTS));
    }

    return g_Events != NULL;
}

**Comment by SinaKarvandi** [comment]
Hi,
Nice catch. Yes, you're right.
Please (if it's possible) open a Pool request (to the Dev branch) and fix it by yourself.

Thanks
