### ISSUE TITLE
SyscallHookHandleUD of SyscallHookHandleUD will blue screen in some versions of the system

### ISSUE THREAD

**Issue by wuhao13** [HyperDbg/HyperDbg#21]
I found that IS_SYSCALL_INSTRUCTION in SyscallHookHandleUD did not judge the instruction length, which would cause a blue screen in some cases due to access to invalid memory.

**Comment by wuhao13** [comment]
The simple fix is as follows
`
		CHAR * InstructionBuffer[3] = { 0 };
		if (InstructionLength == 2)
		{
			MemoryMapperReadMemorySafe(Rip, InstructionBuffer, 2);
			if (IS_SYSCALL_INSTRUCTION(InstructionBuffer))
			{
				__writecr3(OriginalCr3);
				goto EmulateSYSCALL;
			}
		}
		else
		if (InstructionLength == 3)
		{
			MemoryMapperReadMemorySafe(Rip, InstructionBuffer, 3);
			if (IS_SYSRET_INSTRUCTION(InstructionBuffer))
			{
				__writecr3(OriginalCr3);
				goto EmulateSYSRET;
			}
		}
`

**Comment by SinaKarvandi** [comment]
Thanks a lot for your contribution. Honestly, I didn't get what should be changed from the above code. Would you please tell me exactly what has changed?

**Comment by wuhao13** [comment]
First of all, thank you for your help. I am trying to solve this problem. If there is any progress or need support, I will leave a message here

**Comment by wuhao13** [comment]
I have determined the location of the error. The location of the error is in MemoryMapperReadMemorySafe. The specific call stack is:
IdtEmulationHandleExceptionAndNmi->SyscallHookHandleUD->MemoryMapperReadMemorySafe

It seems that MemoryMapperReadMemorySafe has a bug, and here, we don't seem to need to use it.

**Comment by wuhao13** [comment]
`    //
    // Compute the address
    //
    NewAddress = (PVOID)((UINT64)Va + (PAGE_4KB_OFFSET & (PaAddressToRead.QuadPart)));

    //
    // Move the address into the buffer in a safe manner
    //
    memcpy(BufferToSaveMemory, NewAddress, SizeToRead);    < BSOD
`

**Comment by SinaKarvandi** [comment]
I remember Petr @wbenny told me he has the somehow same problem in hvpp, I don't know if it was the same problem but in that case, he solved the problem by injecting #PF to the guest (if I'm not wrong). I'm not sure if it's the reason but that might solve the problem.

**Comment by wbenny** [comment]
If I may interject - yes, it looks like exactly the same symptoms I had and Sina is right about the #PF. You must not read the buffer directly, but rather walk the OS page tables manually to check if they're mapped. If they aren't, then you have to inject #PF.

How it's handled in hvpp: https://github.com/wbenny/hvpp/blob/master/src/hvpp/hvpp/vmexit/vmexit_passthrough.cpp#L1101

```c
 if (auto err_va = vp.guest_read_memory(vp.context().rip, buffer, read_size))
```

If the `guest_read_memory` succeeds, it returns 0. If it fails, it returns the VA of the first unmapped VA.

**Comment by wuhao13** [comment]
@wbenny This problem is actually not that complicated, because the memory page where the RIP is located must be in the physical memory (if they are not in the physical memory, how are they executed?), so we don't need to map the cache, just access it directly.
@SinaKarvandi In addition, I found another bug on my own computer. It seems that there are some problems in the simulation of SYSCALL.

**Comment by wuhao13** [comment]
@SinaKarvandi My test actually confirmed this conjecture. I will provide an anti-virus tool made in China. This tool will almost certainly reproduce this problem on my virtual machine.

Download link: http://down4.huorong.cn/hrsword.exe

**Comment by wbenny** [comment]
Instruction cache and data cache don't necessarily have to be in sync. Also, it could've been paged out by another core.

**Comment by wuhao13** [comment]
I'm sorry, I underestimated the problem

**Comment by wuhao13** [comment]
This is the code I add, you look what I've got it wrong operation?

```
if (MmIsAddressValid(Rip))
{ 
  ...
}
else
{
 goto ReadPageErr;
}

...

Result = SyscallHookEmulateSYSCALL(Regs);

g_GuestState[CoreIndex].IncrementRip = FALSE;
return Result;


VOID
EventInjectPageFaultEx(UINT64 PageFaultAddress)
{
	PAGE_FAULT_ERROR_CODE ErrorCode = {0};
	__writecr2(PageFaultAddress);


	ErrorCode.Fields.Fetch = 0;  
	ErrorCode.Fields.Present = 0; 
	ErrorCode.Fields.Reserved = 0;
	ErrorCode.Fields.User = 1;
	ErrorCode.Fields.Write = 0;
	

	//
	// Error code is from PAGE_FAULT_ERROR_CODE structure
	//
	EventInjectInterruption(INTERRUPT_TYPE_HARDWARE_EXCEPTION, EXCEPTION_VECTOR_PAGE_FAULT, TRUE, ErrorCode.All);
}
```

**Comment by SinaKarvandi** [comment]
I'll try to fix it tomorrow.

**Comment by wbenny** [comment]
I don't think relying on `MmIsAddressValid` is the right thing to do. `MmIsAddressValid` takes into account current `cr3` register, which - at the time of your call - is the hypervisors `cr3`. You have to check validity of the page for the `cr3` of the process that page-faulted.

I guess you can hack it by setting the proper `cr3` before calling `MmIsAddressValid`, but it depends on your taste. I think the best solution would be to create custom function for traversing page-tables with respect to given `cr3` as an argument. Such function will definitelly come in handy sooner or later somewhere else.

**Comment by wuhao13** [comment]
I admit that I used it because I was lazy. ^_^ @wbenny 
Tomorrow I will also try to use your method to solve this problem. Thank you for your help and answers.

**Comment by wuhao13** [comment]
> I'll try to fix it tomorrow.

Thank@SinaKarvandi you. After this problem is solved, there is a more complicated problem that needs to be debugged. When some systems use certain Nt functions, there will be very strange problems when calling syscall, which causes the system process to crash. I am exploring the root of this problem. I hope I can get help from you and @wbenny when I find something.

**Comment by wuhao13** [comment]
I have changed the judging method to use the P bit of PT to judge page faults, and no problems were found after testing.

`
BOOLEAN
CheckNotPageFault(UINT64 va, UINT64 cr3)
{
    CR3_TYPE    TargetCr3;
    TargetCr3.Flags       = cr3;

    /**
    * Interrupt 14—Page-Fault Exception (#PF)
    * The P (present) flag in a page-directory or page-table entry needed for the address translation is clear,
    * indicating that a page table or the page containing the operand is not present in physical memory.
    */
    PPAGE_ENTRY PageEntry = MemoryMapperGetPteVaByCr3(va, PT, TargetCr3);
    if (PageEntry == NULL) 
    {
        return FALSE;
    }
    else
    {
		if (PageEntry->Flags == 0)
		{
			return FALSE;
		}
       if  (PageEntry->Pt.Present == 1)
       {
           return TRUE;
       }
       else
       {
           return FALSE;
       }
    }
}

            if (!CheckNotPageFault(Rip, GuestCr3))
            {
                goto ReadPageErr;
            }
`

**Comment by SinaKarvandi** [comment]
I also pushed a patch.
However, I can't reproduce the problem. Please check if it works with the latest patch or not.
Please test it with Release Build (not Debug Build)

**Comment by SinaKarvandi** [comment]
@wuhao13 Also, not sure if the page-fault error code is correct in the latest patch or not. please verify it too.

**Comment by wuhao13** [comment]
@SinaKarvandi Ok i will test it now

**Comment by wuhao13** [comment]
@SinaKarvandi The code you pushed is the same as the method I implemented. I am not sure whether the U bit of the error code should be 0, but the effect of 0 and 1 in my test is exactly the same.

**Comment by wuhao13** [comment]
I tested successfully on both the virtual machine and the physical host. The problem should have been resolved, I will continue to debug (GuestCr3 & PCID_MASK) == PCID_NONE there is a BSOD, if there is progress, I will resubmit the problem.
In addition, can you optimize the performance of EPT HOOK under patchguard? When I use EPT HOOK, the CPU usage is almost 100%

**Comment by SinaKarvandi** [comment]
Regarding performance, I think I can't do that much as this method of intercepting is not CPU friendly; however, !epthook2 is much better in the case of performance but has its limitations.
Also, did you test it on "Release" build? Is there any problem with !syscall in "release" builds?

**Comment by wuhao13** [comment]
I used the code you updated to test in the framework that I used to streamline documents for testing, and the test results did not have any problems.

**Comment by wuhao13** [comment]
What I mean by ETPhook refers to the use of the Etphook2 hook function. At present, this hook is very inefficient when the PG is running. I guess it may be caused by a large number of #PFs caused by refreshing the TLB.

**Comment by wuhao13** [comment]
@SinaKarvandi Excuse me, can you please provide us with ExtensionCommandChangeAllMsrBitmapReadAllCores(UINT64 BitmapMask) how to use this method? I don't know how to fill in BitmapMask.

**Comment by kanren3** [comment]
> > I'll try to fix it tomorrow.
> 
> Thank@SinaKarvandi you. After this problem is solved, there is a more complicated problem that needs to be debugged. When some systems use certain Nt functions, there will be very strange problems when calling syscall, which causes the system process to crash. I am exploring the root of this problem. I hope I can get help from you and @wbenny when I find something.
> 
> Of course, thank you wbenny for your advice

I have encountered the same problem that calling syscall leads to system process crash, so did you find any further information or event solutions for that? Thanks a lot!

**Comment by wuhao13** [comment]
@kanren3 
Sorry, I didn't find a solution because it seems to be related to CPU vulnerability mitigation
