### ISSUE TITLE
Feature Request: hide memory pages

### ISSUE THREAD

**Issue by romanholidaypancakes** [HyperDbg/HyperDbg#219]
**Is your feature request related to a problem? Please describe.**

- add hide Memory Page command:

  1. Cannot be traversed by techniques such as vad
  1. Even reading `tagrgetAddress` with memcpy returns an exception
     > memcpy(addresss, tagrgetAddress, siZe)
  1. Unable to read using `readprocessmemory`
  1.

- example

  - Hide the specified process memory page (!hidememorypage pid addresss size)

  ```
  !hidememorypage 0x1200 0x7ff8a0478000 0x1000
  ```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by SinaKarvandi** [comment]
Hi,
Thanks a lot for sending this feature request.

Though it seems like a good idea, I can't imagine any use case for it. Can you elaborate on a scenario where this feature can be useful? 

Thanks,

**Comment by SinaKarvandi** [comment]
Hi again,
Sorry for the very late response, I completely missed the notification.

I think I understand what you mean. From my understanding, you mean that this `!hidememory` command should create a copy of the corresponding memory and let the user modify the actual memory. Meanwhile, if there is any read in the memory, the original memory should be shown while the user modifies the actual memory. Am I right?

**Comment by SinaKarvandi** [comment]
Hi again,
I'm pretty sure we're not on the same page. I also asked Satoshi Tanda (from the explanation link) that you provided (https://github.com/tandasat/FU_Hypervisor) and he also believes that this feature will likely crash a program because VAD indicates the address is available, so a program will access without SEH and die.

**Comment by SinaKarvandi** [comment]
I got what you meant. Generally speaking, I believe that this feature is not designed to solve a good portion of problems that will be publicly used. But, I will provide a function in the script engine (which can be used with the !monitor command), and as a result of using that function, you'll be able to inject events (interrupts e.g., #PF) to the hypervisor which will lead to the same functionality that you expect it. This way you can use it to easily implement such behavior, I'll add it to the to-do list for v0.3 .Sounds good?

**Comment by SinaKarvandi** [comment]
Your requested functionalities are added to the HyperDbg.
You can use the '.pagein' command to inject #PF to the guest with a custom error code. 

Please check: 

https://docs.hyperdbg.org/commands/meta-commands/.pagein

Note that, this feature is only supported in the Debugger Mode for now, and available in v0.4. You can test it on the 'dev' branch.
