### ISSUE TITLE
Still EferHOOK~ Still inexplicable DRIVER_IRQL_NOT_LESS_OR_EQUAL

### ISSUE THREAD

**Issue by wuhao13** [HyperDbg/HyperDbg#22]
33: 	PageEntry = MemoryMapperGetPteVaByCr3(Va, PT, TargetCr3);
    34: 
    35: 	if (PageEntry->Present)   <this
    36: 	{
    37: 		return TRUE;
    38: 	}
    39: 	else
    40: 	{

0: kd> DT PageEntry
Local var @ 0xffffdf80fdabed58 Type _PAGE_ENTRY*
0xffffdb00`0032f490 
   +0x000 Flags            : 0x22000001`13d6a125
   +0x000 Pml4             : _PAGE_MAP_LEVEL_4_ENTRY
   +0x000 PdptLarge        : _LARGE_PAGE_DIRECTORY_POINTER_TABLE_ENTRY
   +0x000 Pdpt             : _PAGE_DIRECTORY_POINTER_TABLE_ENTRY
   +0x000 PdLarge          : _LARGE_PAGE_DIRECTORY_ENTRY
   +0x000 Pd               : _PAGE_DIRECTORY_ENTRY
   +0x000 Pt               : _PAGE_TABLE_ENTRY
   +0x000 Present          : 0y1
   +0x000 Write            : 0y0
   +0x000 Supervisor       : 0y1
   +0x000 PageLevelWriteThrough : 0y0
   +0x000 PageLevelCacheDisable : 0y0
   +0x000 Accessed         : 0y1
   +0x000 Dirty            : 0y0
   +0x000 LargePage        : 0y0
   +0x000 Global           : 0y1
   +0x000 Ignored1         : 0y000
   +0x000 PageFrameNumber  : 0y000000000000000100010011110101101010 (0x113d6a)
   +0x000 Reserved1        : 0y0000
   +0x000 Ignored2         : 0y0100000 (0x20)
   +0x000 ProtectionKey    : 0y0100
   +0x000 ExecuteDisable   : 0y0

~_~!
Windows 10 Version 1607

It seems that (GuestCr3.Flags & PCID_MASK) == PCID_NONE has a very strange problem~

**Comment by SinaKarvandi** [comment]
Is it only on Windows 10 1607? do you see this behavior in the nested-virtualization environment too?

**Comment by wuhao13** [comment]
> Is it only on Windows 10 1607? do you see this behavior in the nested-virtualization environment too?

Yes, this system version is very old, but it can be patched but cannot be upgraded to 2002, which means that many people are still using this version.

**Comment by SinaKarvandi** [comment]
The code you mentioned is to make HyperDbg working on a system with the Meltdown patch. The problem might be because of this.

**Comment by wuhao13** [comment]
> The code you mentioned is to make HyperDbg working on a system with the Meltdown patch. The problem might be because of this.
I agree with you, but how should I debug this problem?

**Comment by wuhao13** [comment]
I think the problem is caused by not installing the mitigation patch。

**Comment by wuhao13** [comment]
I have roughly determined the cause of the problem. My CPU is too old and caused a strange problem. I think this problem does not seem to need to be fixed because the I7 2600 is outdated.
