### ISSUE TITLE
Unable to reconnect to hyperdbg

### ISSUE THREAD

**Issue by romanholidaypancakes** [HyperDbg/HyperDbg#228]
**Describe the bug**

**To Reproduce**
1. run hdbg in host
2. run hdbg in guest 
3. press `ctrl+c` and press exit in host to exit hdbg
4. run hdbg in host to reconnect guest

**Expected behavior**
we can reconnect to the guest

**Screenshots**

**Desktop (please complete the following information):**
 -  Latest Dev Branch

**Additional context**

**Comment by SinaKarvandi** [comment]
Please open a new issue and explain it more if the problem still exists. I think it's fixed now. In the 'dev' branch.
