### ISSUE TITLE
error

### ISSUE THREAD

**Issue by gb1dev** [HyperDbg/HyperDbg#229]
nvm

**Comment by SinaKarvandi** [comment]
Hi,
Thanks for creating this issue.
Can you further trace the code in the debuggee (in user mode) to see what goes wrong? I don't have a PC that supports the Serial cable right now. I usually use the virtual serial of the VMware Workstation, but the last time that I test it on a physical system, it worked perfectly. Generally, it would be best if you traced the following function to see where it goes wrong. Please let me know if you understand where is problematic.

![image](https://github.com/HyperDbg/HyperDbg/assets/13383992/d78fa8ca-9715-4885-92c8-30c92d923602)
