### ISSUE TITLE
Expect Hyperdbg to support nested virtualization

### ISSUE THREAD

**Issue by wuhao13** [HyperDbg/HyperDbg#23]
Expect Hyperdbg to support nested virtualization^_^

**Comment by SinaKarvandi** [comment]
Well, it's definitely on our list of future features, but you know, there are hundreds of more important features that need to be added to HyperDbg like BTS, PT, etc.; thus, I think we won't reach to supporting nested-virtualization for at least 2 years.

**Comment by wuhao13** [comment]
I think you should roll a basic version available as soon as possible, so long as there is good availability can attract a lot of people involved in this project

**Comment by SinaKarvandi** [comment]
Yeah, but honestly I don't have any idea about that right now. I have to see how it works and it's time-consuming but I think it's better to put time into other features that will be more useful. Btw, we first have to release the first version of HyperDbg and reach a stable version.

**Comment by wuhao13** [comment]
I have extracted the virtualization code in Hyperdbg and tested it a lot. At least until now, it has performed very well in all aspects. Of course, there is a small problem in removing the EPT HOOK part, I have already submitted this question. Of course, your technology, this problem will be very easy to find during testing.
