### ISSUE TITLE
VMM unloading BSOD

### ISSUE THREAD

**Issue by SinaKarvandi** [HyperDbg/HyperDbg#238]
Set up: I am using Win1022H2 VMware VM (wdk: 10.0.22621.382, sdk: 10.1.22621.755). I disabled DSE, ran the hyperdbg-cli cmd window, and ran the following commands in this order: .connect local, load vmm, unload vmm -> BSOD happens (BSOD error: DRIVER_IRQL_NOT_LESS_OR_EQUAL in hprdbgkd.sys)

**Comment by ThiagoAlexsander** [comment]
Hey, I experienced the problem running the latest version compiled from 'master'
