### ISSUE TITLE
Added A Method To Fix CR0 and CR4 Bits During VMX Operation

### ISSUE THREAD

**Issue by vxcute** [HyperDbg/HyperDbg#25]
Hello All, I Added a Method To The Code To Insure That CR0 and CR4 Registers Not Be Changed During The VMX Operation The IDEA Is Derived From The Intel Manual Here:

![intel](https://user-images.githubusercontent.com/68482847/109338469-fcec1c80-786e-11eb-93bc-eeb41065a33c.PNG)

And The Code Is From https://revers.engineering/day-2-entering-vmx-operation/ However I made Some Changes To It So I Can Follow The Project Coding Style:

```c
  VOID
FixCr4AndCr0Bits()
{
    CR_FIXED Cr_Fixed           = {0};
    CONTROL_REGISTER_4 Cr4      = {0};
    CONTROL_REGISTER_0 Cr0      = {0};

    Cr_Fixed.All = __readmsr(MSR_IA32_VMX_CR0_FIXED0);
    Cr0.Flags    = __readcr0();
    Cr0.Flags |= Cr_Fixed.Split.Low;
    Cr_Fixed.All = __readmsr(MSR_IA32_VMX_CR0_FIXED1);
    Cr0.Flags &= Cr_Fixed.Split.Low;
    __writecr0(Cr0.Flags);
    Cr_Fixed.All = __readmsr(MSR_IA32_VMX_CR4_FIXED0);
    Cr4.Flags = __readcr4();
    Cr4.Flags |= Cr_Fixed.Split.Low;
    Cr_Fixed.All = __readmsr(MSR_IA32_VMX_CR4_FIXED1);
    Cr4.Flags &= Cr_Fixed.Split.Low;
    __writecr4(Cr4.Flags);
}     
```

The Function Can Be Added After Enabling VMX Operation Here => https://github.com/HyperDbg/HyperDbg/blob/37a58fc03fb5ba7ca365991e4bee12bafb92c081/hyperdbg/hprdbghv/VmxRegions.c#L35

Structures Can Be Found Here https://gist.github.com/0xastr0/64446c135cddda13cb26d1dd7d0f4502

Thanks I Hope I Can Contribute More I Really Fall In love with the Project Keep The Good Work ❤

**Comment by SinaKarvandi** [comment]
Thank you for your report. I'll fix it soon. ❤
Also, what happened to your Twitter account? I think it's removed. Is everything okay? We miss you on Twitter.

**Comment by vxcute** [comment]
Hello, I am doing good I removed my Twitter account just to get out of social media a little hahaha anyways good luck I am so excited to see this project released :)

**Comment by vxcute** [comment]
I Translated This to a pull request so it can be easier to maintain u actually got my attention again 😅

**Comment by SinaKarvandi** [comment]
Thanks for your report.
Mereged.
