### ISSUE TITLE
Visual Studio build error 

### ISSUE THREAD

**Issue by simhigo** [HyperDbg/HyperDbg#26]
Visual Studi 2019 / Windows WDK 10 
__writecrc32 C4013 Error 
![image](https://user-images.githubusercontent.com/1684328/109917367-8af55680-7cf8-11eb-8cb7-bbe11be97942.png)

**Comment by SinaKarvandi** [comment]
Hello,
It's weird, did you use --recursive flag when you clone the source code? (might be unrelated)

**Comment by simhigo** [comment]
Yes.  I used "git clone --recursive https://github.com/HyperDbg/HyperDbg.git"

**Comment by SinaKarvandi** [comment]
we never saw such an error, did you use a community or professional version of visual studio?

**Comment by simhigo** [comment]
I used  visual studio professional version

**Comment by SinaKarvandi** [comment]
Hi, sorry for the very late answer.
We had the same issue on #34, and now it's solved.
Please re-test and confirm if the problem is solved for you or not.
Thank you
