### ISSUE TITLE
Unloading Error

### ISSUE THREAD

**Issue by SinaKarvandi** [HyperDbg/HyperDbg#271]
Hey, I experienced the same problem running the latest version compiled from 'master'

_Originally posted by @ThiagoAlexsander in https://github.com/HyperDbg/HyperDbg/issues/238#issuecomment-1741883391_

**Comment by SinaKarvandi** [comment]
Hi @ThiagoAlexsander, 
Thanks for creating this issue. Actually, crashes on unloading VMM can have many reasons and we solved most of these issues over time. It seems to be a new issue. 

Would you please let me know how I can reproduce the error? Or in other words, what commands did you run that caused this error? Please also specify the generations of Intel processors you use and your Windows version. 

Thanks

**Comment by ThiagoAlexsander** [comment]
I tried to reproduce the issue once again but it works now
Maybe it has something to do with this update?
![image](https://github.com/HyperDbg/HyperDbg/assets/40046468/b74fd9a2-d293-4d6f-9791-b572bb6247c8)

**Comment by SinaKarvandi** [comment]
I don't think so. These unloading problems usually happen once users are interacting with the debugger and we forget to for example uninitialize everything correctly, which will be investigated and usually can be easily fixed. Please let me know if you find a way of reproducing these errors so I can reproduce and fix them.
