### ISSUE TITLE
Code that never executes

### ISSUE THREAD

**Issue by ThiagoAlexsander** [HyperDbg/HyperDbg#277]
This piece of code here never gets executed, can't we just remove it?

https://github.com/HyperDbg/HyperDbg/blob/641a9b55c3a00287fe54bab3ce2848cb629147ab/hyperdbg/hprdbghv/code/transparency/Transparency.c#L241C1-L242C39

**Comment by SinaKarvandi** [comment]
Hi,
Good catch!
Yes, you're right. The code can be removed. Go on and remove it and create PR. 👍

**Comment by ThiagoAlexsander** [comment]
#278

**Comment by ThiagoAlexsander** [comment]
#278
