### ISSUE TITLE
Failed to install or load the driver

### ISSUE THREAD

**Issue by kkptm** [HyperDbg/HyperDbg#29]
HyperDbg> .connect local
local debuging current system...

HyperDbg> load vmm
try to install and load the VMM driver...
The CPU Vendor is : GenuineIntel
The Processor virtualization technology is VT-x.
VMX Operation is supported by your processor .
Thread Created successfully !!!
Failed to install or load the driver

HyperDbg> (07:04:24.042 - core : 0 - vmx-root? no) [+] Information (DriverEntry:88) | Hyperdbg is Loaded :)
(07:04:24.042 - core : 0 - vmx-root? no) [+] Information (DriverEntry:103) | Setting device major functions
(07:04:24.042 - core : 3 - vmx-root? no) [+] Information (DrvCreate:218) | Hyperdbg's hypervisor Started...
(07:04:24.042 - core : 3 - vmx-root? no) [+] Information (EptCheckFeatures:54) | *** All EPT features are present ***
(07:04:24.042 - core : 3 - vmx-root? no) [+] Information (VmxInitializer:66) | Your processor supports all EPT features
(07:04:24.042 - core : 3 - vmx-root? no) [+] Information (EptBuildMtrrMap:124) | MTRR Range: Base=0x0 End=0x3fffffffff Type=0x6
(07:04:24.042 - core : 3 - vmx-root? no) [+] Information (EptBuildMtrrMap:124) | MTRR Range: Base=0xc0000000 End=0xffffffff Type=0x0
(07:04:24.042 - core : 3 - vmx-root? no) [+] Information (EptBuildMtrrMap:128) | Total MTRR Ranges Committed: 1
(07:04:24.042 - core : 3 - vmx-root? no) [+] Information (VmxInitializer:76) | Mtrr memory map built successfully
(07:04:24.058 - core : 1 - vmx-root? no) [+] Information (VmxDpcBroadcastAllocateVmxonRegions:28) | Allocating Vmx Regions for logical core 1
(07:04:24.058 - core : 0 - vmx-root? no) [+] Information (VmxDpcBroadcastAllocateVmxonRegions:28) | Allocating Vmx Regions for logical core 0
(07:04:24.058 - core : 2 - vmx-root? no) [+] Information (VmxDpcBroadcastAllocateVmxonRegions:28) | Allocating Vmx Regions for logical core 2
(07:04:24.058 - core : 1 - vmx-root? no) [+] Information (VmxDpcBroadcastAllocateVmxonRegions:35) | VMX-Operation Enabled Successfully
(07:04:24.058 - core : 0 - vmx-root? no) [+] Information (VmxDpcBroadcastAllocateVmxonRegions:35) | VMX-Operation Enabled Successfully
(07:04:24.058 - core : 3 - vmx-root? no) [+] Information (VmxDpcBroadcastAllocateVmxonRegions:28) | Allocating Vmx Regions for logical core 3
(07:04:24.058 - core : 2 - vmx-root? no) [+] Information (VmxDpcBroadcastAllocateVmxonRegions:35) | VMX-Operation Enabled Successfully
(07:04:24.058 - core : 3 - vmx-root? no) [+] Information (VmxDpcBroadcastAllocateVmxonRegions:35) | VMX-Operation Enabled Successfully
(07:04:24.058 - core : 0 - vmx-root? no) [+] Information (VmxAllocateVmxonRegion:109) | VMXON Region Address : ffffdd81088f6000
(07:04:24.058 - core : 0 - vmx-root? no) [+] Information (VmxAllocateVmxonRegion:115) | VMXON Region Physical Address : 238ecd000
(07:04:24.058 - core : 0 - vmx-root? no) [+] Information (VmxAllocateVmxonRegion:121) | Revision Identifier (MSR_IA32_VMX_BASIC - MSR 0x480) : 0x1
(07:04:24.058 - core : 3 - vmx-root? no) [+] Information (VmxAllocateVmxonRegion:109) | VMXON Region Address : ffffdd8108948000
(07:04:24.058 - core : 3 - vmx-root? no) [+] Information (VmxAllocateVmxonRegion:115) | VMXON Region Physical Address : 238eca000
(07:04:24.058 - core : 3 - vmx-root? no) [+] Information (VmxAllocateVmxonRegion:121) | Revision Identifier (MSR_IA32_VMX_BASIC - MSR 0x480) : 0x1
(07:04:24.058 - core : 2 - vmx-root? no) [+] Information (VmxAllocateVmxonRegion:109) | VMXON Region Address : ffffdd810890a000
(07:04:24.058 - core : 2 - vmx-root? no) [+] Information (VmxAllocateVmxonRegion:115) | VMXON Region Physical Address : 238ec7000
(07:04:24.058 - core : 2 - vmx-root? no) [+] Information (VmxAllocateVmxonRegion:121) | Revision Identifier (MSR_IA32_VMX_BASIC - MSR 0x480) : 0x1
(07:04:24.058 - core : 1 - vmx-root? no) [+] Information (VmxAllocateVmxonRegion:109) | VMXON Region Address : ffffdd810844c000
(07:04:24.058 - core : 1 - vmx-root? no) [+] Information (VmxAllocateVmxonRegion:115) | VMXON Region Physical Address : 238ec4000
(07:04:24.058 - core : 1 - vmx-root? no) [+] Information (VmxAllocateVmxonRegion:121) | Revision Identifier (MSR_IA32_VMX_BASIC - MSR 0x480) : 0x1
(07:04:24.058 - core : 0 - vmx-root? no) [+] Information (VmxAllocateVmcsRegion:187) | VMCS Region Address : ffffdd81089b1000
(07:04:24.058 - core : 0 - vmx-root? no) [+] Information (VmxAllocateVmcsRegion:190) | VMCS Region Physical Address : 238ec1000
(07:04:24.058 - core : 0 - vmx-root? no) [+] Information (VmxAllocateVmcsRegion:196) | Revision Identifier (MSR_IA32_VMX_BASIC - MSR 0x480) : 0x1
(07:04:24.058 - core : 3 - vmx-root? no) [+] Information (VmxAllocateVmcsRegion:187) | VMCS Region Address : ffffdd8108951000
(07:04:24.058 - core : 3 - vmx-root? no) [+] Information (VmxAllocateVmcsRegion:190) | VMCS Region Physical Address : 238e9f000
(07:04:24.058 - core : 3 - vmx-root? no) [+] Information (VmxAllocateVmcsRegion:196) | Revision Identifier (MSR_IA32_VMX_BASIC - MSR 0x480) : 0x1
(07:04:24.058 - core : 2 - vmx-root? no) [+] Information (VmxAllocateVmcsRegion:187) | VMCS Region Address : ffffdd8108913000
(07:04:24.058 - core : 2 - vmx-root? no) [+] Information (VmxAllocateVmcsRegion:190) | VMCS Region Physical Address : 238e8f000
(07:04:24.058 - core : 2 - vmx-root? no) [+] Information (VmxAllocateVmcsRegion:196) | Revision Identifier (MSR_IA32_VMX_BASIC - MSR 0x480) : 0x1
(07:04:24.058 - core : 1 - vmx-root? no) [+] Information (VmxAllocateVmcsRegion:187) | VMCS Region Address : ffffdd8108455000
(07:04:24.058 - core : 1 - vmx-root? no) [+] Information (VmxAllocateVmcsRegion:190) | VMCS Region Physical Address : 238e8c000
(07:04:24.058 - core : 1 - vmx-root? no) [+] Information (VmxAllocateVmcsRegion:196) | Revision Identifier (MSR_IA32_VMX_BASIC - MSR 0x480) : 0x1
(07:04:24.058 - core : 0 - vmx-root? no) [+] Information (VmxAllocateVmmStack:237) | Vmm Stack for logical processor : 0xffffa40606c02000
(07:04:24.058 - core : 0 - vmx-root? no) [+] Information (VmxAllocateMsrBitmap:265) | Msr Bitmap Virtual Address : 0xffffa405fddfc000
(07:04:24.058 - core : 0 - vmx-root? no) [+] Information (VmxAllocateMsrBitmap:266) | Msr Bitmap Physical Address : 0x18ca2e000
(07:04:24.058 - core : 0 - vmx-root? no) [+] Information (VmxAllocateIoBitmaps:294) | I/O Bitmap A Virtual Address : 0xffffa405fddfd000
(07:04:24.058 - core : 0 - vmx-root? no) [+] Information (VmxAllocateIoBitmaps:295) | I/O Bitmap A Physical Address : 0x18ca2f000
(07:04:24.058 - core : 0 - vmx-root? no) [+] Information (VmxAllocateIoBitmaps:311) | I/O Bitmap B Virtual Address : 0xffffa405fddfe000
(07:04:24.058 - core : 0 - vmx-root? no) [+] Information (VmxAllocateIoBitmaps:312) | I/O Bitmap B Physical Address : 0x18ca30000
(07:04:24.058 - core : 0 - vmx-root? no) [+] Information (VmxAllocateVmmStack:237) | Vmm Stack for logical processor : 0xffffa40606c0a000
(07:04:24.058 - core : 0 - vmx-root? no) [+] Information (VmxAllocateMsrBitmap:265) | Msr Bitmap Virtual Address : 0xffffa405fddff000
(07:04:24.058 - core : 0 - vmx-root? no) [+] Information (VmxAllocateMsrBitmap:266) | Msr Bitmap Physical Address : 0x18ca39000
(07:04:24.058 - core : 0 - vmx-root? no) [+] Information (VmxAllocateIoBitmaps:294) | I/O Bitmap A Virtual Address : 0xffffa40606c12000
(07:04:24.058 - core : 0 - vmx-root? no) [+] Information (VmxAllocateIoBitmaps:295) | I/O Bitmap A Physical Address : 0x180d3a000
(07:04:24.058 - core : 0 - vmx-root? no) [+] Information (VmxAllocateIoBitmaps:311) | I/O Bitmap B Virtual Address : 0xffffa40606c13000
(07:04:24.058 - core : 0 - vmx-root? no) [+] Information (VmxAllocateIoBitmaps:312) | I/O Bitmap B Physical Address : 0x188c3b000
(07:04:24.058 - core : 0 - vmx-root? no) [+] Information (VmxAllocateVmmStack:237) | Vmm Stack for logical processor : 0xffffa40606c14000
(07:04:24.058 - core : 0 - vmx-root? no) [+] Information (VmxAllocateMsrBitmap:265) | Msr Bitmap Virtual Address : 0xffffa40606c1c000
(07:04:24.058 - core : 0 - vmx-root? no) [+] Information (VmxAllocateMsrBitmap:266) | Msr Bitmap Physical Address : 0x18bf44000
(07:04:24.058 - core : 0 - vmx-root? no) [+] Information (VmxAllocateIoBitmaps:294) | I/O Bitmap A Virtual Address : 0xffffa40606c1d000
(07:04:24.058 - core : 0 - vmx-root? no) [+] Information (VmxAllocateIoBitmaps:295) | I/O Bitmap A Physical Address : 0x186845000
(07:04:24.058 - core : 0 - vmx-root? no) [+] Information (VmxAllocateIoBitmaps:311) | I/O Bitmap B Virtual Address : 0xffffa40606c1e000
(07:04:24.058 - core : 0 - vmx-root? no) [+] Information (VmxAllocateIoBitmaps:312) | I/O Bitmap B Physical Address : 0x188d46000
(07:04:24.058 - core : 0 - vmx-root? no) [+] Information (VmxAllocateVmmStack:237) | Vmm Stack for logical processor : 0xffffa40606c1f000
(07:04:24.058 - core : 0 - vmx-root? no) [+] Information (VmxAllocateMsrBitmap:265) | Msr Bitmap Virtual Address : 0xffffa40606c27000
(07:04:24.058 - core : 0 - vmx-root? no) [+] Information (VmxAllocateMsrBitmap:266) | Msr Bitmap Physical Address : 0x18904f000
(07:04:24.058 - core : 0 - vmx-root? no) [+] Information (VmxAllocateIoBitmaps:294) | I/O Bitmap A Virtual Address : 0xffffa40606c28000
(07:04:24.058 - core : 0 - vmx-root? no) [+] Information (VmxAllocateIoBitmaps:295) | I/O Bitmap A Physical Address : 0x189050000
(07:04:24.058 - core : 0 - vmx-root? no) [+] Information (VmxAllocateIoBitmaps:311) | I/O Bitmap B Virtual Address : 0xffffa40606c29000
(07:04:24.058 - core : 0 - vmx-root? no) [+] Information (VmxAllocateIoBitmaps:312) | I/O Bitmap B Physical Address : 0x188d51000
(07:04:24.058 - core : 1 - vmx-root? no) [+] Information (VmxVirtualizeCurrentSystem:151) | Virtualizing Current System (Logical Core : 0x1)
(07:04:24.058 - core : 0 - vmx-root? no) [+] Information (VmxVirtualizeCurrentSystem:151) | Virtualizing Current System (Logical Core : 0x0)
(07:04:24.058 - core : 2 - vmx-root? no) [+] Information (VmxVirtualizeCurrentSystem:151) | Virtualizing Current System (Logical Core : 0x2)
(07:04:24.058 - core : 1 - vmx-root? no) [+] Information (VmxClearVmcsState:280) | Vmcs Vmclear Status : 0
(07:04:24.058 - core : 3 - vmx-root? no) [+] Information (VmxVirtualizeCurrentSystem:151) | Virtualizing Current System (Logical Core : 0x3)
(07:04:24.058 - core : 0 - vmx-root? no) [+] Information (VmxClearVmcsState:280) | Vmcs Vmclear Status : 0
(07:04:24.058 - core : 2 - vmx-root? no) [+] Information (VmxClearVmcsState:280) | Vmcs Vmclear Status : 0
(07:04:24.058 - core : 1 - vmx-root? no) [+] Information (VmxVirtualizeCurrentSystem:171) | Setting up VMCS for current logical core
(07:04:24.058 - core : 3 - vmx-root? no) [+] Information (VmxClearVmcsState:280) | Vmcs Vmclear Status : 0
(07:04:24.058 - core : 2 - vmx-root? no) [+] Information (VmxVirtualizeCurrentSystem:171) | Setting up VMCS for current logical core
(07:04:24.058 - core : 3 - vmx-root? no) [+] Information (VmxVirtualizeCurrentSystem:171) | Setting up VMCS for current logical core
(07:04:24.058 - core : 0 - vmx-root? no) [+] Information (VmxVirtualizeCurrentSystem:171) | Setting up VMCS for current logical core
(07:04:24.058 - core : 1 - vmx-root? no) [+] Information (VmxSetupVmcs:388) | Cpu Based VM Exec Controls (Based on MSR_IA32_VMX_TRUE_PROCBASED_CTLS) : 0x96006172
(07:04:24.058 - core : 2 - vmx-root? no) [+] Information (VmxSetupVmcs:388) | Cpu Based VM Exec Controls (Based on MSR_IA32_VMX_TRUE_PROCBASED_CTLS) : 0x96006172
(07:04:24.058 - core : 1 - vmx-root? no) [+] Information (VmxSetupVmcs:396) | Secondary Proc Based VM Exec Controls (MSR_IA32_VMX_PROCBASED_CTLS2) : 0x10102a
(07:04:24.058 - core : 2 - vmx-root? no) [+] Information (VmxSetupVmcs:396) | Secondary Proc Based VM Exec Controls (MSR_IA32_VMX_PROCBASED_CTLS2) : 0x10102a
(07:04:24.058 - core : 0 - vmx-root? no) [+] Information (VmxSetupVmcs:388) | Cpu Based VM Exec Controls (Based on MSR_IA32_VMX_TRUE_PROCBASED_CTLS) : 0x96006172
(07:04:24.058 - core : 3 - vmx-root? no) [+] Information (VmxSetupVmcs:388) | Cpu Based VM Exec Controls (Based on MSR_IA32_VMX_TRUE_PROCBASED_CTLS) : 0x96006172
(07:04:24.058 - core : 0 - vmx-root? no) [+] Information (VmxSetupVmcs:396) | Secondary Proc Based VM Exec Controls (MSR_IA32_VMX_PROCBASED_CTLS2) : 0x10102a
(07:04:24.058 - core : 3 - vmx-root? no) [+] Information (VmxSetupVmcs:396) | Secondary Proc Based VM Exec Controls (MSR_IA32_VMX_PROCBASED_CTLS2) : 0x10102a
(07:04:24.058 - core : 1 - vmx-root? no) [+] Information (VmxVirtualizeCurrentSystem:174) | Executing VMLAUNCH on logical core 1
(07:04:24.058 - core : 2 - vmx-root? no) [+] Information (VmxVirtualizeCurrentSystem:174) | Executing VMLAUNCH on logical core 2
(07:04:24.058 - core : 0 - vmx-root? no) [+] Information (VmxVirtualizeCurrentSystem:174) | Executing VMLAUNCH on logical core 0
(07:04:24.058 - core : 3 - vmx-root? no) [+] Information (VmxVirtualizeCurrentSystem:174) | Executing VMLAUNCH on logical core 3
(07:04:24.058 - core : 0 - vmx-root? no) [+] Information (DrvCreate:244) | Hyperdbg's hypervisor loaded successfully :)
(07:04:24.058 - core : 0 - vmx-root? no) [+] Information (DrvCreate:252) | Hyperdbg's debugger loaded successfully
(07:04:24.058 - core : 0 - vmx-root? yes) [+] Information (VmcallTest:457) | VmcallTest called with @param1 = 0x22 , @Param2 = 0x333 , @param3 = 0x4444
i signed all the build files use EV.
it is in vmware, the system vertion is 19042.
except for the previous one, it looks like the load was successful.
but i used command 'bl',it prompted me 'err, setting breakpoints is not possible when you're not connected to a debuggeer'

is there anyone who can help me?

**Comment by SinaKarvandi** [comment]
Hello,
The problem is that you loaded HyperDbg as local debugging and you want to use 'bl' which is a breakpoint-related command!
It's not possible to set breakpoints in local debugging.
In VMI-Mode you can't set breakpoints but you can set breakpoints in Debugger Mode. (https://docs.hyperdbg.com/using-hyperdbg/prerequisites/operation-modes)

Please take a look at (https://docs.hyperdbg.com/getting-started/attach-to-hyperdbg/debug) to create a Debugger Mode connection.
