### ISSUE TITLE
Whether can it be ported to ARM64 platform or not?

### ISSUE THREAD

**Issue by spanishnoobperez** [HyperDbg/HyperDbg#3]

**Comment by SinaKarvandi** [comment]
hello,
Some of the features can be implemented for ARM64 but it would be a completely different project and it's not in my timeline, maybe in the future, maybe.

**Comment by Biswa96** [comment]
Would you like to add the ARM64 platform in all Visual Studio project files? Nothing else.

**Comment by QuietMinder** [comment]
Hope to see the finished product earlier


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Biswapriyo Nath"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月23日(星期六) 中午11:34
收件人:&nbsp;"HyperDbg/HyperDbg"<HHope to see the finished product earlieryperDbg@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [HyperDbg/HyperDbg] Whether can it be ported to ARM64 platform or not? (#3)





 
Would you like to add the ARM64 platform in all Visual Studio project files? Nothing else.

**Comment by SinaKarvandi** [comment]
> Would you like to add the ARM64 platform in all Visual Studio project files? Nothing else.

What do you mean? we use Intel VT-x, it's not for ARM64, neither by design concepts nor instructions.

**Comment by spanishnoobperez** [comment]
Qualcomm ARM64 devices also has an virtualization layer as long as you acquire the permission of EL2 Hypervisior.

**Comment by spanishnoobperez** [comment]
Qualcomm ARM64 devices also have an virtualization layer as long as you acquire the permission of EL2 Hypervisor.

**Comment by spanishnoobperez** [comment]
Qualcomm ARM64 devices also have a virtualization layer as long as you acquire the permission of EL2 Hypervisor.

**Comment by Biswa96** [comment]
I can't even compile this in x64 platform. I'm using latest _stable_ Windows SDK and DDK. There are many symbol duplication error. Should I create another issue or a pull request?
