### ISSUE TITLE
Handle (more) command line arguments to support faster workflows

### ISSUE THREAD

**Issue by snaiperskaya96** [HyperDbg/HyperDbg#304]
**Is your feature request related to a problem? Please describe.**
I'm by no mean an expert so there's a chance there's a better solution to this but whenever I have to start a new hyperdbg session I have to manually type/copy-paste the connection command on both ends and it's getting frustrating over time. 

**Describe the solution you'd like**
Ideally I could make a shortcut to hyperdbg-cli.exe with some arguments such as `--start-cmd=".debug prepare serial..."`. 
I've had a look into the cli code and it seems like it only cares about a single passed argument and that'd be `--script`.

**Describe alternatives you've considered**
Perhaps a local config file where you can specify connection parameters? Sounds like way more work than the above tho.

**Additional context**
Once again i'm not an expert so i'm not sure whether there's a better alternative but I'm currently on a very crashy debug session and I constantly have to run the same command on both ends, it's becoming fairly annoying. On GDB you have both a default config file and a way to pass specific startup instructions via command line, would be nice to have something similar. 

Thanks for all your work on this! It's really promising and I hope I get to use it more.

Cheers,
Jury

**Comment by SinaKarvandi** [comment]
Hi,
Thanks for creating this issue.
Yes, I agree with you. We need to make it easier to connect debuggee and debugger.
I will try to add this feature to HyperDbg.

For now, as a temporary solution, you can create a txt file with your connection string (`debug` command), and run HyperDbg with `--script` and specify the text file path as the parameter.
