### ISSUE TITLE
epthook cannot modify flags 

### ISSUE THREAD

**Issue by w58850** [HyperDbg/HyperDbg#31]
"!epthook 7FF6C81C21A1 pid 37F4 script { @zf = 1; }" wont work

**Comment by SinaKarvandi** [comment]
Hello,
We don't have @zf so your script has the error. Also, I'm not sure if it works on the user-mode address of another process. You can use it for a kernel addresses for now.

**Comment by w58850** [comment]
"!epthook 7FF6C81C21A1 pid 37F4 script {@rip = 7FF6C81C2290; }" works perfectly, but when the process with pid 37F4 exits, there will be many strange problems (such as Bsod), even if I execute "events d 1" and " events c 1".

**Comment by SinaKarvandi** [comment]
Actually, Pid (for events) means that if the event is triggered in another process then ignore it. It doesn't mean to set EPT Hook on that process. I never thought about it. Thanks a lot for reporting it, we will add it to our task lists to support it soon.
For now, you can inject/import HPRDBGCTRL.DLL to your target process and use this feature.

**Comment by SinaKarvandi** [comment]
Hey, 
Unfortunately, it was my mistake, I already solved the problem of running in another process and I run it again and it works perfectly. I mean you can put hidden breakpoint (hook) on other processes.

So, now let's get down to the business. What's the exact problem? and how can I regenerate the problem? Also, please tell me about your Windows version and your processor's generation.

**Comment by SinaKarvandi** [comment]
Please consider to re-open the issue if the error still persists.

**Comment by SinaKarvandi** [comment]
Hi,
Based on your advice, we added the new feature of changing flags from the script engine.

You can see an example here: https://docs.hyperdbg.org/commands/scripting-language/examples/patch-the-normal-sequence-of-execution

Enjoy!
