### ISSUE TITLE
Broken `!cpuid ...` since e605db395253523c611f03b486dc5d9cee6ae983

### ISSUE THREAD

**Issue by sjzbwdiy** [HyperDbg/HyperDbg#324]
**Describe the bug**
Regression

**To Reproduce**
test 0:
1. `git checkout 3b5e361189db585f9d267cb32b407b1824897155`
2. `hyperdbg-cli.exe`
3. `.connect local`
4. `load vmm`
5. `!cpuid pid 0x1F0 script { printf("cpuid: rip(%p), rax(%p), rsp(%p)\n", @rip, @rax, @rsp); }`
6. execute `cpuid` within  pid `0x1F0`
7. problem: no logging

test 1:
1. `git checkout e605db395253523c611f03b486dc5d9cee6ae983`
2. `hyperdbg-cli.exe`
3. `.connect local`
4. `load vmm`
5. `!cpuid pid 0x1F0 script { printf("cpuid: rip(%p), rax(%p), rsp(%p)\n", @rip, @rax, @rsp); }`
6. execute `cpuid` within  pid `0x1F0`
7. problem: no logging

test1:
1. `git checkout e605db395253523c611f03b486dc5d9cee6ae983~1`
2. `hyperdbg-cli.exe`
3. `.connect local`
4. `load vmm`
5. `!cpuid pid 0x1F0 script { printf("cpuid: rip(%p), rax(%p), rsp(%p)\n", @rip, @rax, @rsp); }`
6. execute `cpuid` within  pid `0x1F0`
7. no problem: logging is working

**Expected behavior**
No regression

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win 10 1909
 - Processor Intel i7 6820HQ
 - Version 0.7
 - Environment VMWare Nested Virtualization

**Additional context**
`EfiDSEFix.exe -e 0x8`

**Comment by SinaKarvandi** [comment]
Hi,
Thanks for reporting this issue. 

I tested it with the latest version (v0.7) and it works for me. Can you verify that you didn't pause the inputs (press CTRL+C)? Generally, you should use the 'g' command after pausing the inputs. Another question is, do you have the same problem with the latest 'master' branch (v0.7)?

![image](https://github.com/HyperDbg/HyperDbg/assets/13383992/0c319603-c80b-417a-a9e5-49c3a15a69af)

**Comment by SinaKarvandi** [comment]
Please re-open the issue if the problem still exists.
