### ISSUE TITLE
.debug command error

### ISSUE THREAD

**Issue by botao1995** [HyperDbg/HyperDbg#36]
os version:Win10 x64 1903,

Driver signature has been turned off

HyperDbg-cli tip：
err,startservice failure
unable to install driver
failed to install or load the driver

**Comment by SinaKarvandi** [comment]
Hi again,
Thanks for your report.
Would you please trace the execution in hprdbgctrl and provide the exact error code that causes this failure?

**Comment by botao1995** [comment]
> Hi again,
> Thanks for your report.
> Would you please trace the execution in hprdbgctrl and provide the exact error code that causes this failure?

thank you.

**Comment by SinaKarvandi** [comment]
Is it solved?

**Comment by botao1995** [comment]
> Is it solved?
sorry,no solution
I'm going to try another system
error code 2

**Comment by botao1995** [comment]
> Is it solved?

Is it solved?
sorry,no solution
I'm going to try another system
error code 2

**Comment by botao1995** [comment]
> Is it solved?

sorry,no solution
I'm going to try another system
error code 2

**Comment by botao1995** [comment]
> Is it solved?

**Comment by botao1995** [comment]
> Is it solved?
I follow the documentation steps.
Many methods have been tried and VMware workstation  can not be executed normally. 
![image](https://user-images.githubusercontent.com/47848566/120198346-9226f480-c254-11eb-96d3-dcc0c1ba7c0c.png)
![image](https://user-images.githubusercontent.com/47848566/120198393-9ce18980-c254-11eb-92b4-6d754d4735ef.png)

**Comment by SinaKarvandi** [comment]
The problem is in loading the driver.
Please find the error texts and set breakpoints there, to see what exactly happens that causes the driver loading failure.

**Comment by botao1995** [comment]
> The problem is in loading the driver.
> Please find the error texts and set breakpoints there, to see what exactly happens that causes the driver loading failure.

What kind of system are you?

I think my local machine may be a character set problem，（Chinese win10 system is wide character）

**Comment by botao1995** [comment]
> Is it solved?

this is my test driver. it load success.
![image](https://user-images.githubusercontent.com/47848566/120322643-383b3300-c317-11eb-9394-1518751aa65a.png)
hprdbghv driver load failed.
![image](https://user-images.githubusercontent.com/47848566/120323193-d29b7680-c317-11eb-8a49-07d3c4019af7.png)

**Comment by SinaKarvandi** [comment]
I'm on a skylake (6 gen) machine (1909).
Well, I didn't test it on a Chinese character set but I think the problem might not be because of this.
Error 2 is "The system cannot find the file specified.", So, I think the problem is a simple mistake. The problem comes from the below function:
StartDriver(SC_HANDLE SchSCManager, LPCTSTR DriverName)

You can step through the function and see if the DriverName is valid or not.

**Comment by botao1995** [comment]
> I'm on a skylake (6 gen) machine (1909).
> Well, I didn't test it on a Chinese character set but I think the problem might not be because of this.
> Error 2 is "The system cannot find the file specified.", So, I think the problem is a simple mistake. The problem comes from the below function:
> StartDriver(SC_HANDLE SchSCManager, LPCTSTR DriverName)
> 
> You can step through the function and see if the DriverName is valid or not.

no no no ,I found the reason, not because of the service name. It can't be loaded with the driver loading tool, because the version of ucrtd.lib may be wrong. Although ucrtd.lib can be successfully compiled, the driver sys file can't be loaded. I did a test on my friend's computer, win10 20h2 did not add ucrtd.lib, and sys could be successfully compiled, but if the lower version of win10 did not add ucrtd.lib, there would be the LNK2019 error previously prompted. Now I successfully run hperdbg.sys on this machine！
![image](https://user-images.githubusercontent.com/47848566/120452314-b43f8480-c3c4-11eb-8792-cbb7c664bbc5.png)

![image](https://user-images.githubusercontent.com/47848566/120451779-4bf0a300-c3c4-11eb-81e1-b24a366548c8.png)

**Comment by SinaKarvandi** [comment]
okay, but I didn't get the solution. How can we fix it generally for everyone?

**Comment by botao1995** [comment]
> 好的，但我没有得到解决方案。我们如何才能为所有人解决这个问题？

The current short-term solution is to use a higher system version to compile, this problem still needs to be tried.

**Comment by botao1995** [comment]
> 好的，但我没有得到解决方案。我们如何才能为所有人解决这个问题？



> 好的，但我没有得到解决方案。我们如何才能为所有人解决这个问题？

Or replace the print function in the project

**Comment by botao1995** [comment]
> okay, but I didn't get the solution. How can we fix it generally for everyone?

After my unremitting efforts, I found that I removed ucrtd.lib and added #define _ NO_ CRT_ STDIO_ INLINE to pch. h header file, can be successfully compiled and the driver can be loaded successfully.
![image](https://user-images.githubusercontent.com/47848566/120750597-3650ba00-c539-11eb-9b02-b2d85f741dbb.png)

**Comment by botao1995** [comment]
> okay, but I didn't get the solution. How can we fix it generally for everyone?

After my unremitting efforts, I found that I removed ucrtd.lib and added #define _ NO_ CRT_ STDIO_ INLINE to pch. h header file, can be successfully compiled and the driver can be loaded successfully.
![image](https://user-images.githubusercontent.com/47848566/120754146-d5c47b80-c53e-11eb-8962-158e1a232516.png)

**Comment by SinaKarvandi** [comment]
Thanks for your efforts.
Would you please create a pull request and fix it?

**Comment by botao1995** [comment]
> Thanks for your efforts.
> Would you please create a pull request and fix it?

嗯嗯，ok

**Comment by botao1995** [comment]
> Thanks for your efforts.
> Would you please create a pull request and fix it?

please see also #37
