### ISSUE TITLE
EPT hook has been detected.

### ISSUE THREAD

**Issue by zero-168** [HyperDbg/HyperDbg#360]
I ran into some issues while running HyperDbg in standalone mode.

1.After attempting multiple times to execute EPT hooks on exe modules of games with driver protection, a blue screen was triggered after a few minutes. Analysis of the dump files revealed that the blue screen was caused by the use of the MmGetPhysicalAddress function in the source code, resulting in an IRELAND_NOT_LESS_EQUAL error.
Script code is as follows:
!epthook nt!ZwQuerySystemInformation script {
if($pid == 1cac || $pid == 2cc4) {
if(@rcx == 5) {
if(@r9 != 0) {
ed(@r9,0);
}
@rax = 0xc0000022;
@rip = nt!ZwQuerySystemInformation+1e; //ret
}
}
}

2.Placing an EPT hook on the game's DLL module location would be detected by it. After attempting to place it in multiple locations, all game threads terminated shortly, but the process didn't exit. Task Manager showed 'Access Denied' when attempting to terminate the process, indicating this was caused by its driver. Even if my EPT hook didn't contain any actual executable script code, it would still be detected.

3.Continuing to use the !hide command resulted in the entire system's CPU usage reaching 100%, causing it to freeze.

So, can HyperDbg using VT technology effectively hide processes with driver protection, or would it be detected as before when using EPT?

**Comment by SinaKarvandi** [comment]
Hi,
Thanks for creating issues.

First of all, engaging in cheating during online games is both morally wrong and illegal. HyperDbg is not supposed to be used as an anti-cheat bypass tool!

So, assuming that you're not trying to use it for cheating purposes, I'll give a general answer:

As of now, HyperDbg isn't designed to evade anti-debugging techniques that can detect hypervisor or HyperDbg presence. Implementing such evasion requires lots of work to be done and it's not a primary focus currently.

Our main priorities lie in supporting Linux, enabling HyperDbg to operate during the early boot stages (UEFI), and providing compatibility with AMD processors. 

So, we have ways to reach that kind of stealthness. However, if you know exactly how that specific module works, you could modify HyperDbg to avoid those problems. For example, this is an open-source anti-cheat that is able to detect HyperDbg:

https://github.com/donnaskiez/ac

You can study how it works and apply your necessary modification to HyperDbg's source code to bypass these mitigations.
