### ISSUE TITLE
Doubts on Hypervisors Debuggers & Accelerated Execution Debugging

### ISSUE THREAD

**Issue by pinwhell** [HyperDbg/HyperDbg#363]
i am familiar with debuggers & how they use APIs already to achieve debugging/breakpoints/memory watch-points etc, but , i am new to this type of topic of debugger at hypervisor level, i have a few doubts that have me confused, while reading the description, i think if i understood correctly, that this hypervisor debugger, uses some kind of features to detect page table query's and from that derive a break-point feature, and/or a memory watch-point feature, if thats the case can this also work for example in stuffs executing in accelerated fashion using something Intel VT-x, for example something running inside Virtual Box should be able to be break-pointed with this Hypervisor Debugger, is this the case?

Thanks in advice!!!

**Comment by SinaKarvandi** [comment]
Hi,
Thanks for creating this issue.

>  i think if i understood correctly, that this hypervisor debugger, uses some kind of features to detect page table query's and from that derive a break-point feature, and/or a memory watch-point feature

Yes. HyperDbg uses Intel VT-x capabilities to modify page-table attributes using Extended Page Table (EPT) by employing a second-level page table. More information of how we virtualize an already running system is at: 
https://rayanfam.com/topics/hypervisor-from-scratch-part-7/

> if thats the case can this also work for example in stuffs executing in accelerated fashion using something Intel VT-x, for example something running inside Virtual Box should be able to be break-pointed with this Hypervisor Debugger, is this the case?

Not sure if I correctly understand the question, but in general VirtualBox, VMware Workstation Pro and Player, Hyper-V have a nested virtualization feature. HyperDbg currently supports 1) Physical Machine, 2) VMware Player (free) as well as other VMware products (e.g. Workstation Pro, or ESXi). In these cases, you can also run HyperDbg inside a virtual machine. As an example you can see the video: 
https://docs.hyperdbg.org/getting-started/build-and-install#starting-with-hyperdbg

Please let me know if you have any other questions.

**Comment by pinwhell** [comment]
Thanks
