### ISSUE TITLE
Can not load driver

### ISSUE THREAD

**Issue by ddkwork** [HyperDbg/HyperDbg#378]
**Describe the bug**
Under Win11 x64, with the same signature, I wrote a demo that loads fine, but Hyperdbg fails to load

**To Reproduce**
```go
HyperDbg Debugger [version: v0.9.0, build: 20240612.1314]
Please visit https://docs.hyperdbg.org for more information...
HyperDbg is released under the GNU Public License v3 (GPLv3).

HyperDbg> .connect local
local debugging (vmi-mode)

HyperDbg> load vmm
loading the vmm driver
err, failed loading driver
it's because either the driver signature enforcement is enabled or HVCI prevents the driver from loading
you should disable the driver signature enforcement by attaching WinDbg or from the boot menu
if the driver signature enforcement is disabled, HVCI might prevent the driver from loading
HyperDbg is not compatible with Virtualization Based Security (VBS)
please follow the instructions from: https://docs.hyperdbg.org/getting-started/build-and-install
unable to install VMM driver
failed to install or load the driver

HyperDbg>

```

**Expected behavior**
Load driver success

**Screenshots**
no

**Desktop (please complete the following information):**
 Windows X-Lite (22621.1928) 'Micro 11' By FBConan

**Comment by ddkwork** [comment]
I tested this can be load success
https://github.com/memN0ps/matrix-rs

**Comment by SinaKarvandi** [comment]
Hi,
Are you using HyperDbg from the 'master' branch or the 'dev' branch? or run it from the GitHub built binaries?

**Comment by ddkwork** [comment]
> Hi,\nAre you using HyperDbg from the 'master' branch or the 'dev' branch? or run it from the GitHub built binaries?

Master, version 0.9

**Comment by SinaKarvandi** [comment]
That's weird, I just re-tested it and everything works fine for me.

![image](https://github.com/HyperDbg/HyperDbg/assets/13383992/10f4fd89-516e-4a77-a795-699f81136524)


Can you further investigate it? Are you sure VBS (core isolation) and Hyper-V are disabled? 

Can you check this video as well? 
https://www.youtube.com/watch?v=MDZ9zYfqo50

**Comment by ddkwork** [comment]
Bit of a problem, I've just tried to check within the uninstaller panel that the hv switch is on, but this lite version of Win11 doesn't seem to turn it on. Unfortunately, for Win7 onwards, I can only load any drivers using expired signatures on this version of the lite system, otherwise as described by many open source repository reademe:need to turn off secure boot, turn on test signatures, and open debug ports. These are too much trouble, using signatures saves a lot of steps!

![Screenshot_20240613_113221_com.realvnc.viewer.android.jpg](https://github.com/HyperDbg/HyperDbg/assets/19886504/18a76884-f892-4758-9a09-6f52146e4a4f)

**Comment by ddkwork** [comment]
I can't access YouTube, but my picture shows that you seem to have remote debugging enabled, pipe port configuration and all that, whereas I'm loading the driver directly on the local physical machine, is that a mis-operation? Is it possible to load the driver on the physical machine instead of VMware?

**Comment by ddkwork** [comment]
[hprdbgkd.zip](https://github.com/user-attachments/files/15813408/hprdbgkd.zip)

**Comment by ddkwork** [comment]
They have the same signature, can you test load them on your machine?

**Comment by SinaKarvandi** [comment]
> I can't access YouTube, but my picture shows that you seem to have remote debugging enabled, pipe port configuration and all that, whereas I'm loading the driver directly on the local physical machine, is that a mis-operation? Is it possible to load the driver on the physical machine instead of VMware?

Yes, you can run it on a physical machine in VMI mode. 
Run the following commands:
```
.connect local 
load vmm
```

**Comment by SinaKarvandi** [comment]
Also in your VM you can connect to the VMI mode.

> Bit of a problem, I've just tried to check within the uninstaller panel that the hv switch is on, but this lite version of Win11 doesn't seem to turn it on. Unfortunately, for Win7 onwards, I can only load any drivers using expired signatures on this version of the lite system, otherwise as described by many open source repository reademe:need to turn off secure boot, turn on test signatures, and open debug ports. These are too much trouble, using signatures saves a lot of steps!

I'm not sure if I understand it correctly but usually once the secure boot is on, you cannot change the 'core isolation' settings. You need to turn it off, other than that, what is the state of hyper-v in your system, is it running? You can check it by using 'System Information'.

![image](https://github.com/HyperDbg/HyperDbg/assets/13383992/40a7bf9f-a1a7-4fb3-9177-2581a16b1037)

**Comment by SinaKarvandi** [comment]
> They have the same signature, can you test load them on your machine?

Sure, I'll test it. Also, is it a problem for v0.9? I mean have you used the previous version (like v0.8.4) and was it okay? or all of them have the same problem?

**Comment by ddkwork** [comment]
Hold on, I'll test the vt with ddimon again to see if it's working, just give me a second.

**Comment by ddkwork** [comment]
I was under the impression that the driver could not be loaded since that time period of changing the model of the ept, for a long time, at the same time hyperhide made a logic change of the ept, after his repository was changed he could load the driver but it bsod every time, before that it was normal. I have a vague feeling that this is the case:some compilation parameter is causing the driver loading problem, after successful loading ept should

**Comment by SinaKarvandi** [comment]
No, the error shows that the HyperDbg could not load the driver. It didn't load so the EPT is not modified at all. Could you pls tell me whether Virtualization-based Security (VBS) is active on both your Host and Guest VM? You can check it by using 'System Information' on Windows. Other than that, could you check other ways of disabling Driver Signature Enforcement like described here: https://docs.hyperdbg.org/getting-started/build-and-install#temporarily-disable-dse

**Comment by ddkwork** [comment]
sorry my bad English, my means this commit later

![Screenshot_20240613_122356.jpg](https://github.com/HyperDbg/HyperDbg/assets/19886504/86eca46a-fc83-4e5a-8b48-6a22bac31714)

**Comment by SinaKarvandi** [comment]
> sorry my bad English, my means this commit later
> 
> ![Screenshot_20240613_122356.jpg](https://private-user-images.githubusercontent.com/19886504/339211112-86eca46a-fc83-4e5a-8b48-6a22bac31714.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNTMwNTcsIm5iZiI6MTcxODI1Mjc1NywicGF0aCI6Ii8xOTg4NjUwNC8zMzkyMTExMTItODZlY2E0NmEtZmM4My00ZTVhLThiNDgtNmEyMmJhYzMxNzE0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDA0MjU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhM2I2ODk1OTI1NTBhZDQ5NmRjMDE0ZDNlYjg2N2EyZjdiMzgxZmU2NDViZjEwZDZiYTU0NGRhZTE1Mzk1OGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JDtDVN08aI_rkvaD2SXWgDGdli9JleDK071FRsbI3iw)

Not sure if I get it correctly. Do you mean that HyperDbg couldn't be loaded in your system after this commit? Am I right?

**Comment by ddkwork** [comment]
Yes



---Original---
From: "Sina ***@***.***&gt;
Date: Thu, Jun 13, 2024 12:27 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [HyperDbg/HyperDbg] Can not load driver (Issue #378)




  
sorry my bad English, my means this commit later
 

  
Not sure if I get it correctly. Do you mean that HyperDbg couldn't be loaded in your system after this commit? Am I right?

**Comment by SinaKarvandi** [comment]
How could it be related to not loading the driver? These modifications only come into effect when the driver is loaded. Are we talking about the problem with loading the driver? or are we talking that a BSOD happens once the driver is loaded? 🤔

**Comment by ddkwork** [comment]
![Screenshot_20240613_124043_com.realvnc.viewer.android.jpg](https://github.com/HyperDbg/HyperDbg/assets/19886504/7b149c62-803c-4c6b-bb2e-121d629c4d0c)

ddimon is working

**Comment by SinaKarvandi** [comment]
Could you test it with the GitHub-built artifacts? Do you get the same error (driver not loaded error)?
https://github.com/HyperDbg/HyperDbg/releases/tag/v0.9.0
![image](https://github.com/HyperDbg/HyperDbg/assets/13383992/2e27f2e4-8bbf-4eb1-bcb8-450f50053355)

**Comment by ddkwork** [comment]
Is your Chinese translator still online? Complex descriptions are too difficult in English for me. What I was trying to describe before was:During that commit time period circled in the screenshot, both you and the hyperhide repository applied this multiple ept logic to make the change, since then, I can't load hyperdbg but I can load hyperhide but hyperhide bsods and Hyperdbg fails to load directly, my guess as to whyis due to some compilation parameter.

**Comment by SinaKarvandi** [comment]
> Is your Chinese translator still online? Complex descriptions are too difficult in English for me. What I was trying to describe before was:During that commit time period circled in the screenshot, both you and the hyperhide repository applied this multiple ept logic to make the change, since then, I can't load hyperdbg but I can load hyperhide but hyperhide bsods and Hyperdbg fails to load directly, my guess as to whyis due to some compilation parameter.

I suspect that maybe a previously loaded hyperdbg driver is still in your system that blocks the loading of the new hyperdbg driver?

It's okay pls send your message in Chinese, I will ask a friend to translate it if I didn't understand.

**Comment by ddkwork** [comment]
After testing the loading of several repositories such as driver hello word demo, ddimon, driver written by rust, etc., I confirmed that there is no problem with expired signatures, and that Hyperdbg should indeed have a bug in one of the compilation commands that causes it to fail to load.

**Comment by SinaKarvandi** [comment]
HyperDbg is not signed! Could you check the ddimon's signature and compare it with HyperDbg's signature? 
![image](https://github.com/HyperDbg/HyperDbg/assets/13383992/bd069461-54c6-4954-8f90-6eed6258bd59)

If you want to change it, you need to change the signature for 'hprdbghv', 'kdserial', and 'hprdbgkd'.

**Comment by SinaKarvandi** [comment]
+ hyperlog.

So, here's the drivers that need to be modified (signing):

1. hprdbghv
2. kdserial
3. hprdbgkd
4. hyperlog

**Comment by ddkwork** [comment]
我似乎明白问题的原因了，我一直只签名sys文件，你的意思是dll文件也要签名?



---Original---
From: "Sina ***@***.***&gt;
Date: Thu, Jun 13, 2024 12:52 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [HyperDbg/HyperDbg] Can not load driver (Issue #378)




 
HyperDbg is not signed! Could you check the ddimon's signature and compare it with HyperDbg's signature?
 image.png (view on web)
 
If you want to change it, you need to change the signature for 'hprdbghv', 'kdserial', and 'hprdbgkd'.

**Comment by ddkwork** [comment]
![Screenshot_20240613_125600_com.realvnc.viewer.android.jpg](https://github.com/HyperDbg/HyperDbg/assets/19886504/273a5e53-da71-4eb5-844c-21319684a48b)

我只签名了sys文件，你的意思是其余的dll原因进行内核模式签名吗？

**Comment by ddkwork** [comment]
我将很快测试，谢谢



---Original---
From: "Sina ***@***.***&gt;
Date: Thu, Jun 13, 2024 12:53 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [HyperDbg/HyperDbg] Can not load driver (Issue #378)




  
hyperlog.
  
So, here's the drivers that need to be modified (signing):
  
hprdbghv
 
kdserial
 
hprdbgkd
 
hyperlog

**Comment by SinaKarvandi** [comment]
Yes, I think this could be a problem with the signature. You need to sign all kernel-mode drivers (Test Sign).

是的，我认为这可能是签名的问题。您需要对所有内核模式驱动程序进行签名（Test Sign）。

**Comment by ddkwork** [comment]
![Screenshot_20240613_130645_com.realvnc.viewer.android.jpg](https://github.com/HyperDbg/HyperDbg/assets/19886504/c6a1f1e5-e30f-4747-b777-9dfe48d04118)

加载了，物理机上，把这个写进readme吧，哈哈，原来是需要签名全部文件，我被文件后缀名迷惑了。😅😅😅

**Comment by SinaKarvandi** [comment]
That's great. Yes, I will add a note on Build & Install about this later. Thanks for reporting this.
