### ISSUE TITLE
cmake支持

### ISSUE THREAD

**Issue by ddkwork** [HyperDbg/HyperDbg#382]
**Is your feature request related to a problem? Please describe.**
老实说，vs2022的编码体验非常糟糕，笨重的体积，语法索引卡顿，源代码目录结构混乱且过时，举个例子，vs2022打开hyperdbg仓库的依赖项目录的头文件这个操作，vs2022操作简直令人难以置信，而clion则不管解决方案的工程的层级是怎么划分的，它始终对源代码在硬盘上的真实目录清晰可见，Goland也如此，这将可速度找到自己需要的东西。此外它的编码体验很好，后缀补全，准确快速的语法索引，不会像vs2022动不动就卡住，等待。。。简直是噩梦。加上ai编程助手的支持，clion已经成为我对c和cpp语言的编码首选ide。

**Describe the solution you'd like**
所以我提议:使用
https://github.com/SergiusTheBest/FindWDK
来增加cmake支持。

**Describe alternatives you've considered**

**Additional context**
no more

**Comment by SinaKarvandi** [comment]
Agree. Actually, we need to use CMAKE since HyperDbg is supposed to support Linux for 1 or 2 years.

**Comment by ddkwork** [comment]
```go
file(GLOB_RECURSE C_SOURCES "code/*.cpp")
file(GLOB_RECURSE ASM_SOURCES "code/*.asm")
file(GLOB_RECURSE HEADERS "header/*.h")
enable_language(ASM_MASM)
include_directories(
        "."
        "../include"
        "header"
        "../dependencies"
        "../dependencies/zydis/include"
        "../dependencies/zydis/dependencies/zycore/include"
)

add_library(libhyperdbg   SHARED
        ${C_SOURCES}
        ${ASM_SOURCES}
        ${HEADERS}
)


file(GLOB_RECURSE C_SOURCES "code/*.c")
file(GLOB_RECURSE ASM_SOURCES "code/*.asm")
file(GLOB_RECURSE HEADERS "header/*.h")
enable_language(ASM_MASM)
include_directories(
        "."
        "../include"
        "header"
        "../dependencies"
        "../dependencies/zydis/include"
        "../dependencies/zydis/dependencies/zycore/include"
)

wdk_add_driver(hyperhv
        ${C_SOURCES}
        ${ASM_SOURCES}
        ${HEADERS}
)


```

**Comment by SinaKarvandi** [comment]
Is it the CMAKE file? Am I right? If yes, please create a PR and put it on the 'dev' branch. If you could also make a brief instruction for the users on how to use it, it would be great.

这是 CMAKE 文件吗？我说得对吗？如果是，请创建一个 PR 并将其放在“dev”分支上。如果您还能为用户提供如何使用它的简要说明，那就太好了。

**Comment by ddkwork** [comment]
okay



---原始邮件---
发件人: "Sina ***@***.***&gt;
发送时间: 2024年6月30日(周日) 晚上6:01
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [HyperDbg/HyperDbg] cmake支持 (Issue #382)




 
Is it the CMAKE file? Am I right? If yes, please create a PR and put it on the 'dev' branch. If you could also make a brief instruction for the users on how to use it, it would be great.
 
这是 CMAKE 文件吗？我说得对吗？如果是，请创建一个 PR 并将其放在“dev”分支上。如果您还能为用户提供如何使用它的简要说明，那就太好了。
