### ISSUE TITLE
Remote debugging on physical machine over network

### ISSUE THREAD

**Issue by EmilC3978** [HyperDbg/HyperDbg#386]
Hello,

I would like to know if there is a way to attach to a remote physical machine without a serial cable, like the network kernel debugging functionality of WinDbg. Or to use a virtual COM port over network to kernel debug a remote physical machine.
I have a setup where the target physical machine is not physically accessible, it can be only accessed via network (rdp, ssh,...)

Thank you very much.

**Comment by SinaKarvandi** [comment]
Hi,
Thanks for creating this.

Unfortunately, supporting a kdnet-style debugging is not yet provided in the HyperDbg. You can use the network connection in the VMI Mode by using the '[.connect](https://docs.hyperdbg.org/commands/meta-commands/.connect)' command but it's in [VMI Mode](https://docs.hyperdbg.org/using-hyperdbg/prerequisites/operation-modes#vmi-mode) (local debugging) and doesn't work for the [Debugger Mode](https://docs.hyperdbg.org/using-hyperdbg/prerequisites/operation-modes#debugger-mode). This is a long-standing todo which is not yet added to HyperDbg.

**Comment by EmilC3978** [comment]
Thank you for your prompt response.

**Comment by EmilC3978** [comment]
Thank you for your prompt response.
