### ISSUE TITLE
Make a separate _SYMBOL for the source and destination of '++' and '--' operators

### ISSUE THREAD

**Issue by SinaKarvandi** [HyperDbg/HyperDbg#390]
Hi @xmaple555,

Once you have free time, would please make a modification for the `++` and `--` operators?

Right now, both operands of these operators are available at one _SYMBOL (Both Source and Destination are the same _SYMBOL) which is perfectly fine but it causes problems in hardware debugger (hwdbg).

![image](https://github.com/HyperDbg/HyperDbg/assets/13383992/bac26665-8e39-44d6-8d90-03aa906c961a)

Since, the HyperDbg's hardware debugger (hwdbg) for FPGA and CHIP debugging will be ready soon, based on the current design, it is not possible to use one operand for both the source and the destination. So, I appreciate it if you could modify it in a way that these operators (++, --) have an operand (`Src0`) and one separate destination (`Des`) which is the same as the `Src0`. This way, the hardware debugger could also benefit from these operators.

**Comment by SinaKarvandi** [comment]
The current implementation of the script evaluation engine for hardware is available at: 
https://github.com/HyperDbg/HyperDbg/blob/45b88f652d071e0f3c11b1f84b8a2a2d6556972a/hwdbg/src/main/scala/hwdbg/script/eval.scala#L97

**Comment by xmaple555** [comment]
If IR couldn't accept that source operand and destination operand are same, it means the parser would generate more IR to do the same thing. For example, to do inc, we have to use another temp variable, 
```
INC source, temp
MOV temp, source
```
So definitely, it would be a restriction to design IR.  

In my point of view, if the code execution of IR in hwdbg couldn't accept this situation happened, you can choose to discard dec and inc, and use add or sub to implement them,
```
ADD source, 1, temp
MOV temp, source
```

Of course, this solution couldn't solve the problem fundamentally. You can imagine that some assembly instructions are not available for parser, so uses existing instructions to implement them.

**Comment by SinaKarvandi** [comment]
Yes, I also agree with it since we could use the same addition operator instead of the increment operator.
