### ISSUE TITLE
Please add possibility of putting timestamps within print functions.

### ISSUE THREAD

**Issue by kqikz** [HyperDbg/HyperDbg#397]
Please add possibility of putting timestamps within print functions.

**Comment by SinaKarvandi** [comment]
This one is added as pseudo-register (**$date** and **$time**) at https://github.com/HyperDbg/HyperDbg/commit/b165f56a7b3a797f6766b3329d24b29382880782, please check and if there was any problem, let me know.

![image](https://github.com/HyperDbg/HyperDbg/assets/13383992/c6bc0918-cb46-4344-b686-522b9509f1d2)

**Comment by kqikz** [comment]
All good!
