### ISSUE TITLE
Some questions :)

### ISSUE THREAD

**Issue by Avalon1337** [HyperDbg/HyperDbg#40]
How many !epthooks and !epthook2s can I have? Can I add one to all addresses and generate a trace log?

[edit] I browsed code some and it seems 40 !epthook and infinite !epthook2?

How many bytes can I have in the !epthook (code/condition)?  `!epthook fffff801deadbeef code {90 90 90} condition {90 90 90}`

Where does the code in `!epthook fffff801deadbeef code {90 90 90}` run? Will it be able to modify/update the thread's context, heap etc?

[edit] Does !epthook work for x86 processes?

When will it be released? I can't figure out how to build it due to hprdbghv.inf -- it says Sample class already exists, but you already know that `TODO: edit Class`, so I guess it's to block compilation until it's ready for release? 📦 

[edit] Perhaps it means to use Visual Studio 2015 instead :P

Thanks xD

**Comment by SinaKarvandi** [comment]
Hello,
Sorry for the delayed answer.
 > How many !epthooks and !epthook2s can I have?  
I don't know, but I think even hundreds won't be problematic. And also, what do you mean by 40? I don't remember if I put a limation for !epthook.

> How many bytes can I have in the !epthook (code/condition)? 
There is no limitation, the only limitation might be in transferring buffers. You can also build a customized version of HyperDbg as described here : https://docs.hyperdbg.com/tips-and-tricks/misc/customize-build

> Where does the code in !epthook fffff801deadbeef code {90 90 90} run? Will it be able to modify/update the thread's context, heap etc?

It will be called in vmx-root mode. Of course you can update the context, please read : https://docs.hyperdbg.com/using-hyperdbg/prerequisites/how-to-create-an-action#custom-codes

> Does !epthook work for x86 processes?
Nope, HyperDbg is just for x64 processors. You might modify the implementation and use it in x86 processors too.

> When will it be released? 
Soon, probably next week, we'll release a test version. By the way, it's on a working state. There just might be error but generally everything should be okay.

> I guess it's to block compilation until it's ready for release?
No, you should be able to build it normally. Please take a look at : https://docs.hyperdbg.com/getting-started/build-and-install
and if you still have a problem with building HyperDbg, then create an issue with more details.

Thank you for creating the issue ;)
