### ISSUE TITLE
Event injection of page fault cause bsod

### ISSUE THREAD

**Issue by prnuimeer** [HyperDbg/HyperDbg#403]
Hi, I have another question.
In part8, I did not perform ept memory virtualization, but simply performed several event injections and confirmed that it worked correctly except for page faults.
In page fault event injection, I reuse original error code and the type is specified as hardware exception. 
Afterwards, bsod occurred. I analyzed it and found that the reference to r8 in "mov rax, qword ptr [r8]" of nt!Mifastlockleafpagetable+0x108 was invalid. Do you have any idea? 
(What is interesting is that bsod does not occur when masked with a page fault error code mask. Like that, vmcs of page fault error code mask = 0, page fault error match = -1. It seems to that page fault event injection need more configure unlike other fault event injection, but I didn't find that fact in intel document...)

**Comment by SinaKarvandi** [comment]
Hi,
Are you using HyperDbg for event injection? or Hypervisor From Scratch?

This is how we inject #PF into the guest in HyperDbg which works perfectly fine: 
https://github.com/HyperDbg/HyperDbg/blob/5897065f15a90d70742c063c21b7e219e0c2f8a6/hyperdbg/hprdbghv/code/vmm/vmx/Events.c#L124

and :
https://github.com/HyperDbg/HyperDbg/blob/5897065f15a90d70742c063c21b7e219e0c2f8a6/hyperdbg/hprdbghv/code/vmm/vmx/Events.c#L192

and:
https://github.com/HyperDbg/HyperDbg/blob/5897065f15a90d70742c063c21b7e219e0c2f8a6/hyperdbg/hprdbghv/code/vmm/vmx/Events.c#L281

and this is how we handle page-fault VM-exits:
https://github.com/HyperDbg/HyperDbg/blob/5897065f15a90d70742c063c21b7e219e0c2f8a6/hyperdbg/hprdbghv/code/vmm/vmx/IdtEmulation.c#L316

You can check them for more information. Let me know if there is any other questions.

**Comment by prnuimeer** [comment]
I am sorry, I have been busy lately. I will contact you again after confirmation.
