### ISSUE TITLE
Step over hangs, if process terminates/excepts within call instruction.

### ISSUE THREAD

**Issue by kqikz** [HyperDbg/HyperDbg#406]
[StepOverTst.zip](https://github.com/user-attachments/files/16044713/StepOverTst.zip)
Steps to reproduce:

 .start path C:\dbg\StepOverTst.exe

2: kHyperDbg> bp 00007ff7`54c3156c

2: kHyperDbg> g
debuggee is running...
breakpoint 0x3 hit
00007ff7`54c3156c    E8 37 03 00 00                      call 0x00007FF754C318A8

2: kHyperDbg> p
----

cant do anything now :(

**Comment by SinaKarvandi** [comment]
Hi,
Thanks for reporting this issue.

Fixed at https://github.com/HyperDbg/HyperDbg/commit/386b3e9a109a66e617688a85c3b02f3b371ac9cc

You need to press CTRL+C two times to force pause the debuggee.
Please check the 'dev' branch and re-open the issue if the problem still exists.
