### ISSUE TITLE
Can't set !monitor on same addres, even after event removed.

### ISSUE THREAD

**Issue by kqikz** [HyperDbg/HyperDbg#409]
**hook 1**
1: kHyperDbg> !monitor x 760858a0 l 4 script {
> printf("WS2SEND TRIGGERED\n");
> }

1: kHyperDbg> g
debuggee is running...
WS2SEND TRIGGERED
WS2SEND TRIGGERED
WS2SEND TRIGGERED
WS2SEND TRIGGERED
WS2SEND TRIGGERED
WS2SEND TRIGGERED
WS2SEND TRIGGERED
WS2SEND TRIGGERED
WS2SEND TRIGGERED
WS2SEND TRIGGERED
WS2SEND TRIGGERED
WS2SEND TRIGGERED
fffff804`33ca1282    0F 01 C1                            vmcall

0: kHyperDbg> event c all

0: kHyperDbg> g
debuggee is running...
fffff804`33ca1282    0F 01 C1                            vmcall
**events empty**
1: kHyperDbg> events
no active/disabled events
**here i forgot to switch process**
1: kHyperDbg> !monitor x 760858a0 l 4 script {
> printf("WS2SEND TRIGGERED AGAIN\n");
> }
err, invalid address (c0000005)
address may be paged-out or unavailable on the page table due to 'demand paging'
please refer to https://docs.hyperdbg.org/tips-and-tricks/considerations/accessing-invalid-address for further information

1: kHyperDbg> process pid 22e0
press 'g' to continue the debuggee, if the pid or the process object address is valid then the debuggee will be automatically paused when it attached to the target process

1: kHyperDbg> g
debuggee is running...
switched to the specified process
ntkrnlmp!KiSwapThread+0x81b:
fffff804`36c4164b    45 33 C0                            xor r8d, r8d
**hook2**
0: kHyperDbg> !monitor x 760858a0 l 4 script {
> printf("WS2SEND TRIGGERED AGAIN\n");
> }
err, the page modification is not applied, make sure that you don't put multiple EPT Hooks or Monitors on a single page (c0000026)

0: kHyperDbg>

**Comment by SinaKarvandi** [comment]
Please check this branch and tell me if it's fixed or not: https://github.com/HyperDbg/HyperDbg/tree/fix-monitor-remove

**Comment by kqikz** [comment]
good! i can set monitor on same address again :)
