### ISSUE TITLE
License violation for EPT code from gbhv project

### ISSUE THREAD

**Issue by Gbps** [HyperDbg/HyperDbg#41]
Your EPT code is copied from my project [gbhv](https://github.com/Gbps/gbhv) directly and modified without respecting gbhv's license: [CC 4.0 Attribution License](https://creativecommons.org/licenses/by/4.0/). In addition, your maintainer's name is marked at the top as the author of the code, but the code can be easily matched up 1-to-1 with the original code, with comment styles rewritten or changed.

Here is the code in question:

https://github.com/HyperDbg/HyperDbg/blob/master/hyperdbg/hprdbghv/Ept.c

https://github.com/Gbps/gbhv/blob/master/gbhv/ept.c

In addition, your EPT code is missing a patch that will cause issues on physical systems. 

At line 414:
https://github.com/Gbps/gbhv/blob/master/gbhv/ept.c#L414

The memory type parameters must be copied over in the newly split entries or they will be left uninitialized.

Please put proper attribution to any code used from my project under the CC 4.0 AL terms, and please retain the attribution license for any code re-used in this project.

Thank you.

**Comment by SinaKarvandi** [comment]
Well, yeah, you're right. (!epthook2 command and building the EPT initializers are derived from this project and of course, some of the codes are copied from gbhv), however, !epthook is completely different. I already mentioned the project (gbhv) in Hypervisor From Scratch 7 series. However, I forgot to mention this project in HyperDbg. So, sorry for that, and credits added to the derived parts (https://github.com/HyperDbg/HyperDbg/blob/master/hyperdbg/hprdbghv/Ept.c). Also, please let me know if it needs further modifications.

About the patch, would you please create a pull request and fix it on HyperDbg too?

**Comment by SinaKarvandi** [comment]
Also, I realized the Length Dissembler Engine that was used in this project is not working properly, so I used another LDE for "!epthook2" and it seems that the new implementation is working without error.

**Comment by wuhao13** [comment]
Thank you for your issue, it helped me solve a problem that has plagued me for many days.

**Comment by wuhao13** [comment]
@SinaKarvandi Fixing this bug can solve the problem of abnormal performance of EPTHOOK under the real machine.

**Comment by SinaKarvandi** [comment]
what did you add to fix it? please either send it here or create a pull request.

**Comment by wuhao13** [comment]
@SinaKarvandi 

`EptSplitLargePage`

`    //
    // Make a template for RWX
    //
    EntryTemplate.Flags         = 0;
    EntryTemplate.ReadAccess    = 1;
    EntryTemplate.WriteAccess   = 1;
    EntryTemplate.ExecuteAccess = 1;
    // fix:Copy Memtype <- Add this
    EntryTemplate.MemoryType    = TargetEntry->MemoryType;
    EntryTemplate.IgnorePat     = TargetEntry->IgnorePat;
    EntryTemplate.SuppressVe    = TargetEntry->SuppressVe;`

**Comment by SinaKarvandi** [comment]
Fixed.
