### ISSUE TITLE
Can't set monitors on subsequent calls.

### ISSUE THREAD

**Issue by kqikz** [HyperDbg/HyperDbg#415]
0: kHyperDbg> x ws2_32!send
00000000`**75c658a0**  ws2_32!send

0: kHyperDbg> bp **75c658a0**

0: kHyperDbg> g
debuggee is running...
breakpoint 0x1 hit
ws2_32!send:
00000000`75c658a0    8B FF                               mov edi, edi

1: kHyperDbg> kd
[$+000]   **001bde20**    (from <001bde20>)
[$+004]      0000020c
[$+008]      00aff6d4 (addr <00aff6d4>)
[$+00c]      00000006
[$+010]      00000000
[$+014]      00aff99c (addr <00aff99c>)
[$+018]      00aff8c4 (addr <00aff8c4>)
[$+01c]      00872000 (addr <00872000>)
[$+020]      0000001a
[$+024]      00000001
[$+028]      00000000
[$+02c]      00000000
[$+030]      00000006
[$+034]      02200248
[$+038]      02200220
[$+03c]      02200220
[$+040]      02200220
[$+044]      02680220
[$+048]      02280228
[$+04c]      00001030
[$+050]      02200220
[$+054]      02200220
[$+058]      02200220
[$+05c]      fe51ce60
[$+060]      fe51d19c
[$+064]      fe51d198
[$+068]      00000001
[$+06c]      00000001
[$+070]      00872000 (addr <00872000>)
[$+074]      00e47c80 (addr <00e47c80>)
[$+078]      00e47c80 (addr <00e47c80>)
[$+07c]      00aff064 (addr <00aff064>)
[$+080]      001c1420 (addr <001c1420>)
[$+084]      fed77fdc
[$+088]      fffffffe
[$+08c]      00aff070 (addr <00aff070>)
[$+090]   00227797    (from <00227797>)
[$+094]      fe51d1ec
[$+098]   00213483    (from <00213483>)
[$+09c]      00aff034 (addr <00aff034>)
[$+0a0]      00000000
[$+0a4]      00000000
[$+0a8]      0000001a
[$+0ac]      00000001
[$+0b0]      00aff59c (addr <00aff59c>)
[$+0b4]      00aff7ac (addr <00aff7ac>)
[$+0b8]      00aff7b0 (addr <00aff7b0>)
[$+0bc]      00297098 (addr <00297098>)
[$+0c0]      00872000 (addr <00872000>)
[$+0c4]      00000000
[$+0c8]      00000000
[$+0cc]      0000001a
[$+0d0]      00000001
[$+0d4]      00aff058 (addr <00aff058>)
[$+0d8]   00242ade    (from <00242ade>)
[$+0dc]      00e44858 (addr <00e44858>)
[$+0e0]      00aff0c4 (addr <00aff0c4>)
[$+0e4]   0024dc31    (from <0024dc31>)
[$+0e8]      00000001
[$+0ec]   0024dc26    (from <0024dc26>)
[$+0f0]      fe51d158
[$+0f4]      00aff7b0 (addr <00aff7b0>)
[$+0f8]      00297098 (addr <00297098>)
[$+0fc]      00872000 (addr <00872000>)

1: kHyperDbg> event c all
there is no event

1: kHyperDbg> bl
Id   Address           Status
--   ---------------   --------
01   0000000075c658a0  enabled

1: kHyperDbg> bc 1

1: kHyperDbg> g
debuggee is running...
fffff804`441a1282    0F 01 C1                            vmcall

0: kHyperDbg> process pid 0x1298
press 'g' to continue the debuggee, if the pid or the process object address is valid then the debuggee will be automatically paused when it attached to the target process

0: kHyperDbg> g
debuggee is running...
switched to the specified process
ntkrnlmp!RtlpHpAcquireQueuedLockExclusive+0x26:
fffff804`2a916cc6    8B 05 94 59 9E 00                   mov eax, dword ptr ds:[<ntkrnlmp!KiIrqlFlags (fffff804`2b2fc660)>]

0: kHyperDbg> !monitor x **001bde20** l 3 script {
> printf("pre triggered\n");
> }

0: kHyperDbg> !monitor x **75c658a0** l 3 script {
> printf("triggered\n");
> }

0: kHyperDbg> g
debuggee is running...
**pre triggered**

(13:41:57.655 - core : 1 - vmx-root? yes)        [+] Information (IdtEmulationhandleHostInterrupt:182) | Page-fault received, CR2: 75c658a0
(13:41:57.655 - core : 1 - vmx-root? yes)        [+] Information (IdtEmulationhandleHostInterrupt:182) | Page-fault received, CR2: 75c658a0
(13:41:57.655 - core : 1 - vmx-root? yes)        [+] Information (IdtEmulationhandleHostInterrupt:182) | Page-fault received, CR2: 75c658a0
(13:41:57.671 - core : 1 - vmx-root? yes)        [+] Information (IdtEmulationhandleHostInterrupt:182) | Page-fault received, CR2: 75c658a0
(13:41:57.671 - core : 1 - vmx-root? yes)        [+] Information (IdtEmulationhandleHostInterrupt:182) | Page-fault received, CR2: 75c658a0
(13:41:57.671 - core : 1 - vmx-root? yes)        [+] Information (IdtEmulationhandleHostInterrupt:182) | Page-fault received, CR2: 75c658a0

**[simple_send.zip](https://github.com/user-attachments/files/16118900/simple_send.zip)** (32bit)

**Comment by kqikz** [comment]
1: kHyperDbg> process pid 0x1dfc
press 'g' to continue the debuggee, if the pid or the process object address is valid then the debuggee will be automatically paused when it attached to the target process

1: kHyperDbg> g
debuggee is running...
switched to the specified process
00000000`45994271    81 F6 04 00 00 00                   xor esi, 0x04

0: kHyperDbg> !monitor x 001bde20 l **3** script {
>
> printf("pre triggered\n");
> }
err, invalid address (c0000005)
address may be paged-out or unavailable on the page table due to 'demand paging'
please refer to https://docs.hyperdbg.org/tips-and-tricks/considerations/accessing-invalid-address for further information


looks like odd length may cause this issue

**Comment by SinaKarvandi** [comment]
Hi,
Thanks for creating this issue. It's fixed now: https://github.com/HyperDbg/HyperDbg/commit/c8113aa7964d79026a3dfd9efea5ba3d653cd95f

Please check the latest 'dev' branch commits.

**Comment by kqikz** [comment]
all good
