### ISSUE TITLE
please need to .h file :))

### ISSUE THREAD

**Issue by xSanx** [HyperDbg/HyperDbg#42]
Error C1083 Unable to open file include: Zycore / Format.h: No such file or directory, hprdbgctrl C: \ Users \ Alexander \ Desktop \ HyperDbg-master \ hyperdbg \ hprdbgctrl \ disassembler.cpp 34

**Comment by SinaKarvandi** [comment]
Hello,
You need to clone HyperDbg using --recursive flag for git.
Try to clone it like this : 
`git clone --recursive https://github.com/HyperDbg/HyperDbg.git
`

**Comment by xSanx** [comment]
> Здравствуйте,
> вам нужно клонировать HyperDbg, используя флаг --recursive для git.
> Попробуйте его клонировать вот так:
> `git clone --recursive https://github.com/HyperDbg/HyperDbg.git `

![Снимок](https://user-images.githubusercontent.com/46198990/126422291-1b15273a-6991-455c-bd6e-c9f7fc8e4fdd.PNG)

**Comment by SinaKarvandi** [comment]
Why Microsoft Visual Studio? Try to clone it using regular git. 
Download git from : https://git-scm.com/downloads

**Comment by SinaKarvandi** [comment]
Please re-open the issue if you still have a problem with the building.
