### ISSUE TITLE
can not attach the user-mode application at local machine

### ISSUE THREAD

**Issue by orangice1997** [HyperDbg/HyperDbg#43]
![image](https://user-images.githubusercontent.com/86704705/126866660-9da4a5fe-29d2-473e-9066-40bffe67f70f.png)

**Comment by SinaKarvandi** [comment]
This command is not in a working state. You can only connect to the kernel debugger and trigger breakpoint from the kernel debugger. This command is sth I add to perform my test (which was not successful yet). you should wait for future versions to support this command.

**Comment by orangice1997** [comment]
> This command is not in a working state. You can only connect to the kernel debugger and trigger breakpoint from the kernel debugger. This command is sth I add to perform my test (which was not successful yet). you should wait for future versions to support this command.

Thank you,  can you make a video or an artical to show that how to use hyperdbg to debug an application.

**Comment by SinaKarvandi** [comment]
Yes of course. We're currently working on our academic paper, after that, we'll create videos and lots of articles for that.
