### ISSUE TITLE
The effect of EPTHOOK cannot be sustained effectively.

### ISSUE THREAD

**Issue by hhp9941** [HyperDbg/HyperDbg#439]
Hello！
In VMI mode, 22 EPTHOOKs have been placed at different addresses in the target program. 
However, some hooks become ineffective after running for a while. I can only clear the events and then replace the hooks, and sometimes I even have to reload the VMM for it to work again. 
Additionally, on two different computers with 16GB of RAM each, one computer has a low probability of EPTHOOK failure while the other computer shows a significantly higher failure rate.

I'm not sure if it's due to HyperDbg or the script code itself, but most EPTHOOKs only consist of a single instruction to modify the RIP register.

**Comment by SinaKarvandi** [comment]
Hi,
Thanks for reporting this issue.

Could you provide more details on how we can reproduce the error? Are there any examples of reproducing it?

**Comment by SinaKarvandi** [comment]
Other than that, could you please test it again using the source code from the 'dev' branch? We recently fixed some issues in EPT hooks but those fixes are not yet merged to the 'master' branch.

**Comment by hhp9941** [comment]
Thank you for the solution you provided. I will spend a few days testing the code on the dev branch. However, could the reason for EPTHOOK failing be because the operating system's virtual memory manager swapped the relevant physical memory pages to different physical pages, thereby causing the hook to fail?

**Comment by SinaKarvandi** [comment]
Yes, that's possible. It usually won't happen if you have enough memory (RAM), but in some cases, this might happen.

**Comment by hhp9941** [comment]
After testing, the issue of EPTHOOK instability persists in the dev branch. I conducted tests by disabling the system swap partition, and EPTHOOK remained stable. However, this is not a good idea because continued debugging might lead to system crashes due to insufficient memory. I suggest locking relevant pages throughout the lifecycle of EPTHOOK to prevent them from being paged to disk.

**Comment by SinaKarvandi** [comment]
Thanks for testing it.
Do you have any example codes for locking relevant pages?

**Comment by hhp9941** [comment]
// Axel '0vercl0k' Souchet - March 8 2020
#include <windows.h>
#include<iostream>
#include <cstdint>
#include <cstdio>
#include <memory>
#include <tlhelp32.h>

#pragma comment(lib, "ntdll.lib")


#define NT_SUCCESS(Status) (((NTSTATUS)(Status)) >= 0)

#define MAP_PROCESS 1
#define MAP_SYSTEM 2

extern "C" NTSYSCALLAPI NTSTATUS NTAPI
NtLockVirtualMemory(_In_ HANDLE ProcessHandle, _Inout_ PVOID* BaseAddress,
	_Inout_ PSIZE_T RegionSize, _In_ ULONG MapType);

#define MAX_LEN 20


#include<vector>
using namespace std;
vector<ULONG64> addressList = {
0x144F3D571,
0x144E75A40,
0x1459DAF81,
0x1459DAD63,
0x144DC9877,
0x144DB84D5,
0x144DCB5F6,
0x144DCB5E6,
0x144E439FF,
0x144E435A8,
0x144E435E0,

};
int main(int Argc, const char* Argv[]) {

	while (true)
	{
		DWORD ProcessID = 0;
		printf("Please enter a process ID.");
		scanf_s("%d", &ProcessID);
		const HANDLE Process =
			OpenProcess(PROCESS_SET_QUOTA | PROCESS_QUERY_INFORMATION |
				PROCESS_VM_OPERATION,
				false, ProcessID);
		if (Process == NULL)
		{
			std::cout << "Failed to open the process. The target process has permission protection.\n";
			continue;
		}
		for (size_t i = 0; i < addressList.size(); i++)
		{
			PVOID BaseAddress = (PVOID)addressList[i];
			SIZE_T RegionSize = MAX_LEN;
		again:
			const NTSTATUS Status =
				NtLockVirtualMemory(Process, &BaseAddress, &RegionSize, MAP_PROCESS);

			if (NT_SUCCESS(Status)) {

				printf("Page locked successfully.\n");
				//return true;
			}
			else if (0xc00000a1 == Status)
			{
				SIZE_T minWorkingSetSize, maxWorkingSetSize;
				if (!GetProcessWorkingSetSize(Process, &minWorkingSetSize, &maxWorkingSetSize)) {
					// 处理错误
					std::cout << "GetProcessWorkingSetSize failed\n";
					continue;
				}
				SIZE_T newMinWorkingSetSize = minWorkingSetSize + (100 * 1024 * 1024); // Add 100MB.
				SIZE_T newMaxWorkingSetSize = maxWorkingSetSize + (100 * 1024 * 1024); // Add 100MB.

				if (!SetProcessWorkingSetSize(Process, newMinWorkingSetSize, newMaxWorkingSetSize)) {
					// 处理错误
					std::cout << "SetProcessWorkingSetSize failed\n";
					continue;
				}
				goto again;
			}
			else
			{
				std::cout << "Failed. Address:" << BaseAddress << "retValue:" << Status << std::endl;
			}
		}


	}
	return EXIT_SUCCESS;
}

**Comment by hhp9941** [comment]
It works very well, making the EPT hook for R3-level applications stable. However, the only thing to note is the OpenProcess function: if the target program has permission protection, you will need to perform privilege escalation.

**Comment by SinaKarvandi** [comment]
This is a user-mode code. We need to find an equivalent for the kernel which needs to be ANY IRQL compatible.
