### ISSUE TITLE
Win 1909 Could not load vmm

### ISSUE THREAD

**Issue by 906675869** [HyperDbg/HyperDbg#448]
First of all, thanks of opensouce so wonderful dbg.
somehow, when I try to test some function, I got some problem.

I am quite sure that I follow the quick start 
1.My pc Support vm
2.I used EfiGuard boot And I disable DSE and VBS Get the result 
F:\>EfiDSEFix.exe -d
Disabling DSE...
CI!g_CiOptions at 0xFFFFF800233C7278.
Successfully disabled DSE. Original g_CiOptions value: 0x6

AND I check the system info Get the Success result :
IS NOT START

3. But When I'm trying to load vmm Get Results is 
HyperDbg> .connect local
local debugging (vmi-mode)

HyperDbg> load vmm
loading the vmm driver
err, StartService failure (7f)
unable to install VMM driver
failed to install or load the driver

emmmmm,
I am not sure if any else I could do to fix this. Or this framework is not suitable for win10 1909.
If any tips would be thankful.

**Comment by SinaKarvandi** [comment]
Hi,
Thanks for creating this issue.

Error, 0x7f is this one: 
![image](https://github.com/user-attachments/assets/05dbae18-0bc7-49de-9fff-319dda3a51d9)

I don't know why it happens but the Windows version is a little bit old, which might cause this problem. One solution might be to build HyperDbg using an older SDK in the target system in 1909.

**Comment by 906675869** [comment]
OK, I'd try this after my work, thank you for your reply.

**Comment by SinaKarvandi** [comment]
Do you mean the problem is because of Windows SDK? What happens on each update? I thought SDK came with backward compatibility.
