### ISSUE TITLE
Debug assertion failed

### ISSUE THREAD

**Issue by franciscolinan** [HyperDbg/HyperDbg#45]
**Describe the bug**
Debug assertion failed when running command db 3BFAD05C l 10 pid 2624.

**To Reproduce**
1. .connect local
2. .load vmm
3. db 3BFAD05C l 10 pid 2624

**Screenshots**
![image](https://user-images.githubusercontent.com/81978144/127730564-07074d42-fc83-4a1b-b070-76e62900c99b.png)

**Desktop:**
 - OS: [Microsoft Windows 10 Home]
 - Processor [Intel Core i7-8750H]
 - Version [10.0.19362 Build 18362]
 - Environment [Local debugging]

**Additional context**
If I click abort or retry, the console freezes and I can't close it.
Also I get invalid address when I run !monitor on a usermode address.

**Comment by SinaKarvandi** [comment]
Yep, I can reproduce the error. Thanks for reporting, it will be solved soon.

**Comment by SinaKarvandi** [comment]
The problem is solved in the last commit.
Please re-open the issue if the issue is not fixed.

Thanks again for reporting it. :)
