### ISSUE TITLE
Script engine bugs on order of passing arguments to functions

### ISSUE THREAD

**Issue by SinaKarvandi** [HyperDbg/HyperDbg#453]
Hi,
I was creating automatic tests for the functions in the script engine and I realized that the order of passing arguments to functions is wrong, for example, this code:

```
? {

  //
  // Test case activation
  //
  test_case60 = 1;
  test_case61 = 1;
  test_case62 = 1;
  test_case63 = 1;
  test_case64 = 1;
  test_case65 = 1;
  test_case66 = 1;
  test_case67 = 1;
  test_case68 = 1;
  test_case69 = 1;

  //
  // Test case configuration
  //
  current_test_case = 0n59;

  //
  // Make the environment ready 
  //
  variable_equal_to_55 = 0x55;

  /* ======================================================================= */

  //
  // Test case 60 (function definition)
  //
  current_test_case = current_test_case + 1;

  //
  // Create a global variable
  //
  .my_test_func_global_var = 12;

  void my_func_test(int var1, int var2, int var3) {
    printf("var1 is equal to : %llx\n", var1);
    printf("var2 is equal to : %llx\n", var2);
    printf("var3 is equal to : %llx\n", var3);
    .my_test_func_global_var = .my_test_func_global_var + var1 - var2;
    return;
    printf("this statement is never shown!\n");
  }

  do {

    if (test_case60 != 1) {
      break;
    }

    my_func_test(1, 2, 3);

    printf(".my_test_func_global_var is equal to : %llx\n", .my_test_func_global_var);
    if (.my_test_func_global_var == 11) {
      printf("test case %d was successful\n", current_test_case);
    } else {
      printf("test case %d was failed\n", current_test_case);
      break;
    }

  }
  while (0);

  /* ======================================================================= */

}
```

The result is:

![image](https://github.com/user-attachments/assets/5ccc7a8b-bb6f-400c-8bdd-6701b32ec641)

But the correct order of parameters should be: 

```
var1 is equal to : 1
var2 is equal to : 2
var3 is equal to : 3
```

**Comment by xmaple555** [comment]
checkout the branch script-engine

**Comment by SinaKarvandi** [comment]
Okay, thank you. Is there any specific reason why you didn't merge it?

Right now, I'm working on making test cases for most of HyperDbg's functionalities. Together with @Abbas-MG, we're trying to integrate the [new command parser](https://github.com/HyperDbg/HyperDbg/tree/integrate-new-parser) to HyperDbg. Right now, I'm making test cases for the parser.

Also, I just created a couple of somehow complex test cases for the script engine's function available here:
https://github.com/HyperDbg/script-engine-test/blob/main/semantic-test-cases/manual-test-cases_60-69.ds

![image](https://github.com/user-attachments/assets/233c4656-eaa5-41c2-b40a-ad62ab77ed0e)

Some of them failed, and some of them also made different values in each execution, so it seems that there are some problems there. If you find free time, please take a look at these test cases as well. Thank you.

**Comment by SinaKarvandi** [comment]
Got it. Thanks, I'll fix those problems.

**Comment by SinaKarvandi** [comment]
I resolved the issues with both the factorial and memcpy functions, but it seems the problem is still there. Feel free to check it out when you have time. It's not urgent at all.

**Comment by SinaKarvandi** [comment]
Everything seems to be fixed. Nice job. 👍
