### ISSUE TITLE
remote debugger (Wmare 16 pro)

### ISSUE THREAD

**Issue by xSanx** [HyperDbg/HyperDbg#46]
for your manual, i connected with wmvare...
![Снимок](https://user-images.githubusercontent.com/46198990/127893694-d58eeb3b-648a-470c-81fa-2a50755b74f2.JPG)
![Снимок2](https://user-images.githubusercontent.com/46198990/127893746-5eb53c9b-a2c5-447c-a2bd-cedda72d6d00.JPG)
but none of the commands work ...
![Снимок3](https://user-images.githubusercontent.com/46198990/127893773-794615e2-322b-4790-919f-7707c4e6a1a4.JPG)
![Снимок4](https://user-images.githubusercontent.com/46198990/127893791-dcef7be5-2abd-4521-b605-aea0756424e1.JPG)
![Снимок5](https://user-images.githubusercontent.com/46198990/127893811-846c49da-86c7-4e2d-a896-8ed864096e41.JPG)
ssdt hooks causes BSOD
![Снимок6](https://user-images.githubusercontent.com/46198990/127893822-4965fd84-50b6-43fe-b510-4faab41f8c4e.JPG)

**Comment by xSanx** [comment]
example for "hypervisor from scratch part 8" also BSOD for use SysCallHook

**Comment by SinaKarvandi** [comment]
What's your processor model and Windows version?
Are you sure that the address is valid (please verify it using Windbg).

And also, what happens in WinDbg when you use !syscall command. Please send the detail of the crash for further investgation.

**Comment by xSanx** [comment]
Windows 10 Kernel Version 19041 MP (1 procs) Free x64
Built by: 19041.1.amd64fre.vb_release.191206-1406
proccessor : intel i5 7300HQ
![Безымянный](https://user-images.githubusercontent.com/46198990/128120268-f748de6d-bc94-4c93-aa49-01ac266926f7.png)

**Comment by SinaKarvandi** [comment]
Thank you for sending the picture, but please send the result of `!analyze -v ` command from WinDbg, this command indicates the exact reason of the error. Another thing that comes to my mind, the command that you used has a conflict with patch guard so in the case you didn't run windbg at the very first step of the boot, then a BSOD might happen. Another thing is the memory manager feature of `!syscall` command which is sometimes problematic, you can also test `!syscall2` to see if it works or not.

**Comment by xSanx** [comment]
I apologize for the long business trip reply. I figured out what the error was, I configured the virtual machine incorrectly. But the question remained for !syscall(!syscall2), I get this output:
![Снимок](https://user-images.githubusercontent.com/46198990/128983798-f9dba60e-4a1f-48a7-b26c-d0d43dedf289.JPG)


what is the address 00007fff`d5f2d7c2 and what is it 0F 05 and how to disable !syscall(!syscall2)?

**Comment by xSanx** [comment]
also after running on a protected vmprotest, the debugger is interrupted at each next step:
![Снимок](https://user-images.githubusercontent.com/46198990/128989169-ae5aa58b-72ba-4df3-bc39-609d611d7d5a.JPG)

how to continue the OS execution?

**Comment by SinaKarvandi** [comment]
About the first question, you set the debugger to break on each system call. so, each time a SYSCALL happens then debugger breaks the execution.

If you want to create a log from each syscall the use something like this :
`!syscall pid 4 script { printf("syscall number is : %llx\n", @rax); }`

And if you want to disable the event, use the '[event](https://docs.hyperdbg.com/commands/debugging-commands/events)' command like [this](https://docs.hyperdbg.com/tips-and-tricks/misc/enable-and-disable-events-in-debugger-mode).

**Comment by SinaKarvandi** [comment]
> also after running on a protected application (vmprotest) the debugger is interrupted at each next step:
> ![Снимок](https://user-images.githubusercontent.com/46198990/128989169-ae5aa58b-72ba-4df3-bc39-609d611d7d5a.JPG)
> 
> how to continue the OS execution?

Is there any active event in HyperDbg? What is 'vmprotest'? is it 'vmprotect'?

**Comment by xSanx** [comment]
> > также после запуска в защищенном приложении (vmprotest) отладчик прерывается на каждом следующем шаге:
> > ![Снимок](https://user-images.githubusercontent.com/46198990/128989169-ae5aa58b-72ba-4df3-bc39-609d611d7d5a.JPG)
> > как продолжить выполнение ОС?
> 
> Есть ли какое-нибудь активное событие в HyperDbg? Что такое vmprotest? это «vmprotect»?
no, there are no active events. Software starts with protection Vmprotect. Vmprotect https://vmpsoft.com/

**Comment by SinaKarvandi** [comment]
Well, that's probably an anti-VM technique that tries to deny HyperDbg from debugging. I don't know what's exactly happening there.

**Comment by xSanx** [comment]
is it possible to somehow find out the place of the kernel function call?

**Comment by SinaKarvandi** [comment]
I didn't get the point, "the place of the kernel function call" of what ?

**Comment by xSanx** [comment]
how to get id of the thread r/w/e by the hooked address?

**Comment by SinaKarvandi** [comment]
add an script to your event command : 

... `script { print($tid); }`

**Comment by xSanx** [comment]
and if you need to find out the driver calling kernel functions or modifying kernel structures?

**Comment by SinaKarvandi** [comment]
Please don't hesitate to open new issues if you have any questions.
