### ISSUE TITLE
Invalid Physical Address Error in !monitor

### ISSUE THREAD

**Issue by WenMaoLin** [HyperDbg/HyperDbg#469]
**Describe the bug**
The address 7FFDDF8000 is a valid MMIO address, but when using!monitor, it returns the error: err, invalid physical address (c0000052)`.

**Screenshots**
![image](https://github.com/user-attachments/assets/70df7b5d-3aaf-4fb1-948f-ac7a98da63eb)

 - OS: [Win11 23H2 22631.4037]
 - Processor [Intel I5 13600KF]
 - Version [v0.10.0, build: 20240722.0348]
 - Environment [Physical Machine]

**Comment by SinaKarvandi** [comment]
Thanks for reporting this issue. 

It was a miscomputation of the physical address width which is now fixed and available at the dev branch.

Here's the patch:
https://github.com/HyperDbg/HyperDbg/commit/418f375ba0a779d762edef303c6ea4d4c65ed04c
