### ISSUE TITLE
syscall?

### ISSUE THREAD

**Issue by hhuiwang** [HyperDbg/HyperDbg#472]
carry out !syscall How to continue running after the command? The  bl command displays "Breakpoints list is empty". Also not mentioned in the documentation

**Comment by SinaKarvandi** [comment]
Hi,
I couldn't quite understand the question. The !syscall command is not related to the 'bl' command. You need to use the '[events](https://docs.hyperdbg.org/commands/debugging-commands/events)' command for the '!syscall' events.

**Comment by hhuiwang** [comment]
Thanks, I thought it was a bd command disable !syscall. (Sorry, the text comes from the translation software, which has caused you some trouble)

**Comment by SinaKarvandi** [comment]
No problem
