### ISSUE TITLE
kdnet not work

### ISSUE THREAD

**Issue by shiguowang** [HyperDbg/HyperDbg#476]
Following the tutorial below, I installed kdnet, but it doesn't work.Can you give me some clues to solve this problem?
https://docs.hyperdbg.org/getting-started/build-and-install

error message：
![image](https://github.com/user-attachments/assets/5d806f8f-dfb2-48be-a679-9f1d76756dd2)

my network card information:
![image](https://github.com/user-attachments/assets/6ee4c22c-1a6a-482b-a04f-0667effc0454)

**Comment by SinaKarvandi** [comment]
Hello,
Thanks for creating this issue.

It's a problem most likely with your Ethernet card. But that's not a big deal, you still have plenty of other options like disabling Driver Signature Enforcement from the boot menu or even better using EfiGuard. None of them need kdnet.

Please take a look at this video, it shows you how to set up EfiGuard:

https://youtu.be/MDZ9zYfqo50?si=F4MdjilMYzkepCrC

Other than that, don't hesitate to ask any other questions if you have.

**Comment by shiguowang** [comment]
Thanks for your help SinaKarvandi.

EfiGuard works very well. From my tests as if this method is more general.

For "kdnet" I used the latest version of windows SDK(10.0.26100), But still doesn't work.

**Comment by shiguowang** [comment]
close this issue as question solved.
