### ISSUE TITLE
I have a question for you.

### ISSUE THREAD

**Issue by wuhao13** [HyperDbg/HyperDbg#49]
if (GuestRegs->r10 == 0x48564653 && GuestRegs->r11 == 0x564d43414c4c && GuestRegs->r12 == 0x4e4f485950455256)

Where do these constants come from in this code? I did not find these constants in SYS.

**Comment by SinaKarvandi** [comment]
These are some random constants so we can make sure that the VMCALL should be handled by HyperDbg. If the VMCALL doesn't have these constants we can assume that we're operating on a nested-virtualization environment and that VMCALL should be passed to the top-level hypervisor

**Comment by wuhao13** [comment]
@SinaKarvandi Thank you, I'm investigating the issue that occasionally causes other applications to suddenly crash when the VT framework is uninstalled.
