### ISSUE TITLE
A small modification

### ISSUE THREAD

**Issue by wuhao13** [HyperDbg/HyperDbg#50]
I have debugged and passed the xmm code in AsmVmexitHandler.asm, it no longer has a blue screen, the code is as follows:

`
;------------------------------------------------------------------------
AsmVmexitHandler PROC
    
    push 0  

    pushfq  ; 8 Byte

    ; ------------ Save XMM Registers ------------
    ;   
    ;   ;;;;;;;;;;;; 16 Byte * 16 Byte = 256 + 4  = 260 (0x106 == 0x110 but let's align it to have better performance) ;;;;;;;;;;;;

       sub     rsp, 0110h
    ;
       movaps  xmmword ptr [rsp+000h], xmm0    ; each xmm register 128 bit (16 Byte)
       movaps  xmmword ptr [rsp+010h], xmm1
       movaps  xmmword ptr [rsp+020h], xmm2
       movaps  xmmword ptr [rsp+030h], xmm3
       movaps  xmmword ptr [rsp+040h], xmm4
       movaps  xmmword ptr [rsp+050h], xmm5
       movaps  xmmword ptr [rsp+060h], xmm6 
       movaps  xmmword ptr [rsp+070h], xmm7
       movaps  xmmword ptr [rsp+080h], xmm8
       movaps  xmmword ptr [rsp+090h], xmm9
       movaps  xmmword ptr [rsp+0a0h], xmm10
       movaps  xmmword ptr [rsp+0b0h], xmm11
       movaps  xmmword ptr [rsp+0c0h], xmm12
       movaps  xmmword ptr [rsp+0d0h], xmm13
       movaps  xmmword ptr [rsp+0e0h], xmm14
       movaps  xmmword ptr [rsp+0f0h], xmm15  
       stmxcsr dword ptr [rsp+0100h]           ; MxCsr is 4 Byte
    ;
    ;---------------------------------------------
	; 16 * 8 Byte = 128 = 0x80
    push r15
    push r14
    push r13
    push r12
    push r11
    push r10
    push r9
    push r8        
    push rdi
    push rsi
    push rbp
    push rbp	; rsp
    push rbx
    push rdx
    push rcx
    push rax	

	mov rcx, rsp		; Fast call argument to PGUEST_REGS
	sub	rsp, 28h		; Free some space for Shadow Section
	call	VmxVmexitHandler
	add	rsp, 28h		; Restore the state

	cmp	al, 1	
	je		AsmVmxoffHandler

	RestoreState:
	
	pop rax
    pop rcx
    pop rdx
    pop rbx
    pop rbp		; rsp
    pop rbp
    pop rsi
    pop rdi 
    pop r8
    pop r9
    pop r10
    pop r11
    pop r12
    pop r13
    pop r14
    pop r15

    ; ------------ Restor XMM Registers ------------
    ;
       movaps xmm0, xmmword ptr [rsp+000h]
       movaps xmm1, xmmword ptr [rsp+010h]
       movaps xmm2, xmmword ptr [rsp+020h]
       movaps xmm3, xmmword ptr [rsp+030h]
       movaps xmm4, xmmword ptr [rsp+040h]
       movaps xmm5, xmmword ptr [rsp+050h]
       movaps xmm6, xmmword ptr [rsp+060h]
       movaps xmm7, xmmword ptr [rsp+070h]
       movaps xmm8, xmmword ptr [rsp+080h]
       movaps xmm9, xmmword ptr [rsp+090h]
       movaps xmm10, xmmword ptr [rsp+0a0h]
       movaps xmm11, xmmword ptr [rsp+0b0h]
       movaps xmm12, xmmword ptr [rsp+0c0h]
       movaps xmm13, xmmword ptr [rsp+0d0h]
       movaps xmm14, xmmword ptr [rsp+0e0h]
       movaps xmm15, xmmword ptr [rsp+0f0h]
    
       ldmxcsr dword ptr [rsp+0100h]          
       
       add     rsp, 0110h
    ; ----------------------------------------------

    popfq

	sub rsp, 0100h   
	jmp VmxVmresume

AsmVmexitHandler ENDP

;------------------------------------------------------------------------

AsmVmxoffHandler PROC
    sub rsp, 020h       ; shadow space
    call HvReturnStackPointerForVmxoff
    add rsp, 020h       ; remove for shadow space

    mov [rsp+198h], rax  

    sub rsp, 020h       ; shadow space
    call HvReturnInstructionPointerForVmxoff 
    add rsp, 020h       ; remove for shadow space

    mov rdx, rsp        ; save current rsp 

    mov rbx, [rsp+198h] ; read rsp again 

    mov rsp, rbx		

    push rax         

    mov rsp, rdx       
                        
    sub rbx,08h         
    mov [rsp+198h], rbx

	RestoreState:

	pop rax
    pop rcx
    pop rdx
    pop rbx
    pop rbp		         ; rsp
    pop rbp
    pop rsi
    pop rdi 
    pop r8
    pop r9
    pop r10
    pop r11
    pop r12
    pop r13
    pop r14
    pop r15

    ; ------------ Restor XMM Registers ------------
	;
        movaps xmm0, xmmword ptr [rsp+000h]
        movaps xmm1, xmmword ptr [rsp+010h]
        movaps xmm2, xmmword ptr [rsp+020h]
        movaps xmm3, xmmword ptr [rsp+030h]
        movaps xmm4, xmmword ptr [rsp+040h]
        movaps xmm5, xmmword ptr [rsp+050h]
        movaps xmm6, xmmword ptr [rsp+060h]
        movaps xmm7, xmmword ptr [rsp+070h]
        movaps xmm8, xmmword ptr [rsp+080h]
        movaps xmm9, xmmword ptr [rsp+090h]
        movaps xmm10, xmmword ptr [rsp+0a0h]
        movaps xmm11, xmmword ptr [rsp+0b0h]
        movaps xmm12, xmmword ptr [rsp+0c0h]
        movaps xmm13, xmmword ptr [rsp+0d0h]
        movaps xmm14, xmmword ptr [rsp+0e0h]
        movaps xmm15, xmmword ptr [rsp+0f0h]
	
        ldmxcsr dword ptr [rsp+0100h]          
    ;    
        add     rsp, 0110h
    ; ----------------------------------------------

    popfq

	pop		rsp     ; 
	ret             ; jump back to where we called Vmcall

AsmVmxoffHandler ENDP

;------------------------------------------------------------------------

END
`

**Comment by SinaKarvandi** [comment]
Hello,
Thanks for the code, but is there any special problem that makes you dump XMM registers?
I mean, they need many cycles to process, and as we don't use them or modify them, there is no need to dump them.

Actually, I think you see BSOD because of optimization for the compilers. If you disable optimization for the release compiler then you won't see BSOD. (in HyperDbg we already disabled them.)

**Comment by wuhao13** [comment]
Yes, I know we don’t need to save these registers for the time being. Maybe they will never be used, but in my mind, I feel very insecure if I don't save them.

**Comment by SinaKarvandi** [comment]
By default, you are not allowed to use floating-point registers in kernel-mode drivers. (and the reason is performance issues).

So, I think you should also avoid saving these registers which makes your computer substantially slower. I know what you mean, but it's better to avoid wasting millions of cycles on each VM-exit. :)

**Comment by wuhao13** [comment]
You let me learn new knowledge. Thank you, I will remove it now.
