### ISSUE TITLE
kernel mode debugger

### ISSUE THREAD

**Issue by xSanx** [HyperDbg/HyperDbg#55]
hello this debugger is a great thing! This is really a huge work ... There is a question about debugging the kernel on a physical machine ... is it possible to debug kernel functions from VMI-mode, maybe through scripts ...? did not find information in the help...

**Comment by SinaKarvandi** [comment]
Hello,
Thanks a lot for your feedback.

You can do whatever you want in VMI-Mode except breaking (halting) the debugger. It means that you can write a script to create a log from the states (registers, memory, etc.) and also you can modify registers or memory but you can't halt it to get a new command from the debugger. All in all, you can put a hook but you can't put a breakpoint in this mode.

**Comment by xSanx** [comment]
how can you intercept the return from a function in kernel mode? for example ExAllocatePoolWithTag and is it possible then from VMI -mode?

**Comment by SinaKarvandi** [comment]
Yep, it's possible, you should put a !epthook on the `ret` instruction of **ExAllocatePoolWithTag** and for example print the **RAX** of it using a script.

`!epthook AddressOfRetOnExAllocatePoolWithTag script { printf("return register is : %llx\n", @rax);  }`

Note that you should replace the `AddressOfRetOnExAllocatePoolWithTag` address.

**Comment by xSanx** [comment]
Can I change any values from VMI mode?

**Comment by SinaKarvandi** [comment]
You can change both memory and registers from the script engine.

Use the following link for an explanation about changing the register(s) : 
https://docs.hyperdbg.com/commands/scripting-language/variables-and-assignments#registers-assignment

And the following link to change the memory : 
https://docs.hyperdbg.com/commands/scripting-language/functions/memory/eb-ed-eq

This is a list of supported registers : 
https://docs.hyperdbg.com/commands/scripting-language/assumptions-and-evaluations#registers


But we're currently testing the registers manipulation section, it's done but not tested yet. I'm pretty sure the testing for this section will be finished next week, so please check it next week.

**Comment by SinaKarvandi** [comment]
Please don't hesitate to open new issues if you have further questions.
