### ISSUE TITLE
!cpuid pid in VMI-mode

### ISSUE THREAD

**Issue by xSanx** [HyperDbg/HyperDbg#56]
Hi. Using MyHypervisorApp from part3 tried to intercept the command CPUID using !cpuid pid 9484 script{ printf("return register is : %llx\n", @rax);} in VMI-mode but "hook" didn't work. What am I doing wrong? Thank you

**Comment by SinaKarvandi** [comment]
Hello,
`MyHypervisorApp` is from Hypervisor from scratch tutorials, `HyperDbg` is a completely different project. `MyHypervisorApp` won't get any command, as it's just an example, it's not a debugger. Use HyperDbg instead.

**Comment by xSanx** [comment]
sorry :)) I probably put it wrong .))  I use Hyperdbg to intercept the command CPUID . Application "MyHypervisorApp" calls this command from user mode but !Cpuid pid 9484 script {printf ("return register is:% llx \ n", @Rax );}  does not work.

**Comment by SinaKarvandi** [comment]
As long as I know, "MyHypervisorApp" executes the CPUID instruction at the very first steps of execution. So, it means you probably won't get the CPUID when you set the !cpuid as the application finished execution of this instruction. Try to use a sample project that waits till you give a command and then execute the CPUID (while you set the !cpuid command).

**Comment by xSanx** [comment]
I run «MyHypervisorApp» in x64dbg I go through the instruction but there is no reaction from Hyperdbg
