### ISSUE TITLE
Defeating Anti-Debug & Anti-Hypervisor Methods

### ISSUE THREAD

**Issue by xSanx** [HyperDbg/HyperDbg#57]
Hey! Tell me what functions does it use hyperdbg to hide its presence in the system? CPUID? rdtsc?

**Comment by SinaKarvandi** [comment]
Do you mean the functions in the code? or the commands?

https://docs.hyperdbg.com/using-hyperdbg/examples/defeating-anti-debug-and-anti-hypervisor-methods

**Comment by xSanx** [comment]
function in code...

**Comment by SinaKarvandi** [comment]
https://github.com/HyperDbg/HyperDbg/blob/55db553a08ae6f6a4d42362b4d5146cc3dac8c6b/hyperdbg/hprdbghv/Source%20Files/Debugger/Transparency/Transparency.c#L510

and all of the functions are in this file : 
https://github.com/HyperDbg/HyperDbg/blob/master/hyperdbg/hprdbghv/Source%20Files/Debugger/Transparency/Transparency.c
