### ISSUE TITLE
HyperDbg应用程序如何在Windows 7中?

### ISSUE THREAD

**Issue by lingdianvision** [HyperDbg/HyperDbg#59]
In the documentation, I am not found HyperDbg support kernel

**Comment by SinaKarvandi** [comment]
Hello,
What do you mean by "HyperDbg support kernel"? Do you mean debugging kernel-mode (a remote guest machine) using HyperDbg?

**Comment by SinaKarvandi** [comment]
Also, we never tested HyperDbg on any Windows other than Win 10. However, theoretically, there should not be any problem with other Windows like 7 or 8.

**Comment by lingdianvision** [comment]
I can't successfully loaded driver on Windows 7, GetLastError returns 127 .

**Comment by lingdianvision** [comment]
Thank you very much for your prompt reply
![ERR127](https://user-images.githubusercontent.com/28745428/135354689-91684b93-a9de-4ae6-a801-5d36457b6501.png)

**Comment by SinaKarvandi** [comment]
It's a Windows error, this link might be helpful :
https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/1d4ea956-5bd9-476b-8df5-1022a5d6d3e4/startservice-127?forum=wdk

**Comment by SinaKarvandi** [comment]
If the issue persists you can re-open it.
