### ISSUE TITLE
windows 11 build error.

### ISSUE THREAD

**Issue by pxps** [HyperDbg/HyperDbg#61]
OS: WIndows  11
IED: VS2019
WIN SDK version: 10.0.22000.194
WDK version: 10.0.22000.194

![image](https://user-images.githubusercontent.com/26179643/137642361-38ebf780-e550-4b0f-9d4e-30882c83c1fb.png)

**Comment by SinaKarvandi** [comment]
Are you building iti on a visual studio on Win 11

**Comment by pxps** [comment]
yep

**Comment by Myonium** [comment]
Same here:
Window 10
Visual Studio Community 2019
Windows SDK 10.0.22000.194
Windows Driver Kit 10.0.22000.1

![grafik](https://user-images.githubusercontent.com/16895607/139663466-fdc49207-3f9f-418b-9feb-5c0d663e30fc.png)

**Comment by Myonium** [comment]
It seems to be a WDK issue 
Windows SDK 10.0.18362.1
Windows Driver K 10.0.18362.1 
works ...

**Comment by SinaKarvandi** [comment]
Unfortunately, it seems Microsoft stopped exporting those Hvi* functions in the newest version of SDK. I'm working to see if I can find a way to provide these functions for kdhv.lib

**Comment by SinaKarvandi** [comment]
@pxps @Myonium 

We fix this problem by creating empty functions for those missing functions.
Please `git pull` the latest commit and tell me if you can compile it or not.

Thanks

**Comment by pxps** [comment]
My system has been switched back to Win10 @SinaKarvandi

**Comment by pxps** [comment]
@Myonium Help me test it, thank you.

**Comment by SinaKarvandi** [comment]
No problem, it's most likely solved. I test it and verified it on Win 11 SDK.
