### ISSUE TITLE
BSOD when attaching to System process

### ISSUE THREAD

**Issue by lain3d** [HyperDbg/HyperDbg#63]
**Describe the bug**
Not able to attach to system process. Also not able to print out syscalls of pid 4.

**To Reproduce**
1. Connect in debugger mode with namepipe 
2. Use .process pid 4
3. Use 'g' to continue guest
4. bsod

**Expected behavior**
I expected breaking to stop in pid 4 system like mentioned here: "By default, HyperDbg is spinning on vmx-root, and the default process is the system process pid = 4" -- but it is hyperdbg-cli.exe. 

This prompted me to try logging syscalls like in #46 .
```!syscall pid 4 script { printf("syscall number is : %llx\n", @rax); }```
Expected to be able to log syscalls of pid 4, but no sycsalls print. 

Syscalls do print if I set pid to hyperdbg-cli.exe as expected.

I've both disabled driver enforcement and attached windbg like mentioned for !syscall in the docs.

**Screenshots**
Instead here's a pastebin link to the !analyze -v:
https://pastebin.com/uTj7jwjD

**Desktop (please complete the following information):**
 - OS: Tried 19042 and 18362 
 - Processor: 8700k
 - Commit 962bf17
 - Environment: VMWare Nested Virtualization (Workstation 16 pro)

**Comment by SinaKarvandi** [comment]
Hello,
Thanks for creating such a detailed issue.
> By default, HyperDbg is spinning on vmx-root, and the default process is the system process pid = 4

By this sentence, the memory layout of the process is the same as the system process. The current process might be anything, but the **cr3** is the system's **cr3**. I also added a little extra explanation to the '.process' documentation to avoid confusion.

About :
`!syscall pid 4 script { printf("syscall number is : %llx\n", @rax); }`

As long as I know, the system process doesn't invoke any syscalls. However, I have never confirmed it yet. Please tell me if I'm wrong.

About the '`.process pid 4`',
Yep, I can confirm the error. It'll be fixed soon. I'll notify you of this issue when it's solved.

Again, thanks for creating this issue.

**Comment by SinaKarvandi** [comment]
Please `git pull` to the latest commit and check the "`.process pid xx`" command again.

This command is completely redesigned, and I think the new design is better as it's more CPU dependant than Windows (APC/DPC) dependant.

It uses MOV TO CR3 to detect any process change.

Please re-check the documentation as it's completely changed.
https://docs.hyperdbg.org/commands/meta-commands/.process

Also, this command will be improved in the future, and we will add things like showing a list of `EPROCESS` etc.

**Comment by lain3d** [comment]
I can confirm that ".process pid 4" no longer causes a bugcheck 👍
