### ISSUE TITLE
hyperdbg-cli does not compile

### ISSUE THREAD

**Issue by JstBora** [HyperDbg/HyperDbg#65]
> No file digest algorithm specidied. Please specify the digest algorithm with the /fd flag. Using /fd SHA256 is recommended and more secure than SHA1. Calling signtool with /fd sha1 is equivalent to the previous behavior. In order to select the hash algorithm used in the signing certificate signature, use the /fd certHash option.

I looked in the project properties to select /fd sha256 but couldn't find it. Is there any other way to solve this?

**Comment by SinaKarvandi** [comment]
Hi,
Try to turn off signing.
![Capture](https://user-images.githubusercontent.com/13383992/140707946-a9df96cd-11e1-49be-9f8a-a3e07f0d8ee7.PNG)

**Comment by JstBora** [comment]
Thanks Sina 👍
