### ISSUE TITLE
VMWare Fusion 12.2.0 not supported?

### ISSUE THREAD

**Issue by Myonium** [HyperDbg/HyperDbg#66]
I'm trying the following Setup
 * Host OSX Big Sur (11.6)
 * VMWare Fusion 12.2.0
 * Client Windosw 10 (10.0.18363)
 
VMWare settings according the documentation [https://docs.hyperdbg.org/using-hyperdbg/examples/connecting-to-hyperdbg]
It seems to work:
```
HyperDbg> .connect local
local debugging (vmi-mode)

HyperDbg> load vmm
loading the vmm driver
current processor vendor is : GenuineIntel
virtualization technology is vt-x
vmx operation is supported by your processor
vmm module is running...
please configure the symbol path (use '.help .sympath' for more information)
```
As soon as it hits a hook such as:
```
!epthook nt!NtOpenFile pid 1A4 script {
        printf("%ws\n", dq(poi(r8 + 10) + 0x8));
}
```
I get a blue screen of the Windows 10 client ... 

Anybody experiences with Fusion ... should that work?

**Comment by SinaKarvandi** [comment]
Thanks for creating the issue.

No, we didn't test it on VMware Fusion but there shouldn't be any problem as the vmm module is loaded.
Would you please try to run your script like this :
`!epthook nt!NtOpenFile script {  printf("%llx\n", @r8); } `

I wanna know whether the problem is because of the script engine's `printf` with `%ws` or it's a problem with EPT hook implementation.

Thanks,

**Comment by Myonium** [comment]
Mmmm tried it ... same thing:
```
!epthook nt!NtOpenFile script { printf("%llx\n", @r8); }
```
It is setting the hook ... but blue screen'ing as soon as a event is triggered ...

**Comment by SinaKarvandi** [comment]
Well, can you attach a WinDbg and give the result of `!analyze -v`. It's because I don't know what exactly is happening there.

**Comment by Myonium** [comment]
I need a different setup ... As Windows is crashing (blue screen) I'm loosing the debugger session ...

**Comment by SinaKarvandi** [comment]
Is there any dump for the crashes? Maybe Windows saved a Minidump and the dump can be opened with a WinDbg to analyze.

**Comment by DarkerSquirrel** [comment]
Hello Sina

Crashing occured to me without VMWARE (running it in native Win10) when running:
!epthook nt!NtOpenFile pid 12249 script {
        printf("%ws\n", dq(poi(r8 + 10) + 0x8));
}
This doesnt crash imediately ,it takes few tens of seconds, while printing various filenames.

I have **11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz   2.80 GHz**
Windows 10 Pro 20H2 19042.1348

No minidumps were created , just a huge c:\windows\memory.dmp , you can download it from:
https://mega.nz/file/uh82na7K#JkUIvQylBOFC4gccvkF7TKLKf6WmO53rQAW9cvUOW9s

Running !epthook nt!NtOpenFile script { printf("%llx\n", @r8); } didn't trigger any crash so far.

Thanks

**Comment by SinaKarvandi** [comment]
Hello, Thanks a lot for the issue. 
I moved it to a new new issue here : https://github.com/HyperDbg/HyperDbg/issues/86
