### ISSUE TITLE
Windows driver test-signing mode detect

### ISSUE THREAD

**Issue by pxps** [HyperDbg/HyperDbg#67]
When debugging some special programs in driver **test-signing mode**, it will be detected. Can you bypass this detection?

**Comment by SinaKarvandi** [comment]
Hi,
Which command exactly? Do you mean !syscall or !sysret?

**Comment by pxps** [comment]
@SinaKarvandi 
I can join you in the development

**Comment by SinaKarvandi** [comment]
> @SinaKarvandi I mean **test-signing** mode. Some programs will be tested when debugging in **test-signing** mode

Sorry, I still don't understand what you mean. Do you mean that HyperDbg is detected by anti-hypervisor methods?

> @SinaKarvandi I can join you in the development
It's our pleasure to have you on our team. Would you please send me an email to sina@rayanfam.com so, we can discuss it?
